import { Extension, InputRule, Node as TiptapNode, mergeAttributes } from '@tiptap/core'
import Highlight from '@tiptap/extension-highlight'
import Image from '@tiptap/extension-image'
import Link from '@tiptap/extension-link'
import { Mathematics } from '@tiptap/extension-mathematics'
import Placeholder from '@tiptap/extension-placeholder'
import { TableKit } from '@tiptap/extension-table'
import TaskItem from '@tiptap/extension-task-item'
import TaskList from '@tiptap/extension-task-list'
import Underline from '@tiptap/extension-underline'
import { EditorContent, useEditor } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import { Plugin, TextSelection } from '@tiptap/pm/state'
import { useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import 'katex/dist/katex.min.css'

import { Icon } from '../../shared/components/Icon'
import { FloatingLayer } from '../../shared/components/Overlay'
import type { NoteDto, TagDto, VersionedDocument } from '../../shared/tauri/contracts'
import { SUPPORTED_TOP_LEVEL_NODES, normalizeDocument, toTiptapDocument } from './document'
import { PhycatCodeBlock, phycatCodeLanguages, phycatLanguageIcon } from './phycatCode'

export type EditorChange = { title: string; documentJson: VersionedDocument }
const StableBlockIds=Extension.create({name:'stableBlockIds',addGlobalAttributes(){return[{types:[...SUPPORTED_TOP_LEVEL_NODES],attributes:{blockId:{default:null,parseHTML:element=>element.getAttribute('data-block-id'),renderHTML:attributes=>attributes.blockId?{'data-block-id':attributes.blockId,tabindex:'-1'}:{}}}}]},addProseMirrorPlugins(){return[new Plugin({appendTransaction:(_transactions,_oldState,state)=>{const transaction=state.tr;let changed=false;state.doc.forEach((node,offset)=>{if(SUPPORTED_TOP_LEVEL_NODES.has(node.type.name)&&!node.attrs.blockId){transaction.setNodeMarkup(offset,undefined,{...node.attrs,blockId:crypto.randomUUID()});changed=true}});return changed?transaction:null}})]}})
const MarkdownMathShortcuts=Extension.create({name:'markdownMathShortcuts',priority:1100,addInputRules(){return[
  new InputRule({find:/^\$\$([^$\n]+)\$\$$/,handler:({state,range,match})=>{const $from=state.doc.resolve(range.from);state.tr.replaceWith($from.before(),$from.after(),state.schema.nodes.blockMath.create({latex:match[1].trim()}))}}),
  new InputRule({find:/(?<!\$)\$([^$\n]+)\$$/,handler:({state,range,match})=>{state.tr.replaceWith(range.from,range.to,state.schema.nodes.inlineMath.create({latex:match[1].trim()}))}}),
]}})
const MermaidNode=TiptapNode.create({name:'mermaid',group:'block',atom:true,draggable:true,addAttributes(){return{source:{default:'graph TD\n  A[开始] --> B[完成]',parseHTML:element=>element.getAttribute('data-source')??'',renderHTML:attrs=>({'data-source':attrs.source})}}},parseHTML(){return[{tag:'div[data-type="mermaid"]'}]},renderHTML({HTMLAttributes}){return['div',mergeAttributes(HTMLAttributes,{'data-type':'mermaid',class:'mermaid-diagram'})]},addNodeView(){return({node})=>{const dom=document.createElement('div');dom.className='mermaid-diagram';dom.setAttribute('contenteditable','false');let current=node;const render=async()=>{try{const module=await import('mermaid');module.default.initialize({startOnLoad:false,securityLevel:'strict',theme:document.documentElement.dataset.theme==='dark'?'dark':'neutral'});const result=await module.default.render(`coolnote-mermaid-${crypto.randomUUID()}`,current.attrs.source);dom.innerHTML=result.svg;dom.classList.remove('is-error')}catch{dom.textContent=current.attrs.source;dom.classList.add('is-error')}};void render();return{dom,update:next=>{if(next.type.name!=='mermaid')return false;current=next;void render();return true}}}}})

type Props={note:NoteDto;availableTags:TagDto[];focusTitle?:boolean;onChange:(change:EditorChange)=>void;onTagsChange:(tagIds:string[])=>void;onCreateTag:(name:string)=>Promise<TagDto>;onAddAttachment:(file:File)=>Promise<string>}
type Point={left:number;top:number}
type SlashState=Point&{query:string}
type InputLayer={kind:'link'|'inlineMath'|'blockMath'|'mermaid'|'tag';value:string}|null
function CodeLanguageIcon({language}:{language:string}){const icon=phycatLanguageIcon(language);return icon?<span className={`code-language-icon ty-file-icon ty-fi-${icon.name}`} aria-hidden="true">{Array.from({length:icon.layers},(_,index)=><span className={`path${index+1}`} key={index}/>)}</span>:null}
type FindPanel={replace:boolean;query:string;replacement:string;index:number}|null
type TextMatch={from:number;to:number}
type SlashItem={id:string;section:'基础块'|'媒体与高级内容';name:string;copy:string;icon?:string;badge?:string;keywords?:string;run?:(editor:any)=>void}

const leaveList=(editor:any,chain:any)=>editor.isActive('taskList')?chain.toggleTaskList():editor.isActive('bulletList')?chain.toggleBulletList():editor.isActive('orderedList')?chain.toggleOrderedList():chain
const setTextBlock=(editor:any,kind:'paragraph'|'heading'|'blockquote'|'codeBlock',level?:number)=>{let chain=leaveList(editor,editor.chain().focus());if(editor.isActive('blockquote')&&kind!=='blockquote')chain=chain.toggleBlockquote();if(editor.isActive('codeBlock')&&kind!=='codeBlock')chain=chain.toggleCodeBlock();if(kind==='paragraph')chain.setParagraph().run();else if(kind==='heading')chain.setHeading({level}).run();else if(kind==='blockquote'&&!editor.isActive('blockquote'))chain.toggleBlockquote().run();else if(kind==='codeBlock'&&!editor.isActive('codeBlock'))chain.toggleCodeBlock().run();else chain.run()}
const slashItems:SlashItem[]=[
  {id:'paragraph',section:'基础块',name:'正文',copy:'普通文本段落',icon:'file-text',keywords:'文本 paragraph',run:e=>setTextBlock(e,'paragraph')},
  ...([1,2,3,4,5] as const).map(level=>({id:`heading-${level}`,section:'基础块' as const,name:`${['一','二','三','四','五'][level-1]}级标题`,copy:level<3?'章节标题':'层级标题',keywords:`标题 h${level}`,badge:`H${level}`,run:(e:any)=>setTextBlock(e,'heading',level)})),
  {id:'bullet-list',section:'基础块',name:'无序列表',copy:'项目符号列表',icon:'list',keywords:'列表 bullet',run:e=>{if(!e.isActive('bulletList'))e.chain().focus().toggleBulletList().run()}},
  {id:'ordered-list',section:'基础块',name:'有序列表',copy:'数字编号列表',icon:'list-ordered',keywords:'列表 ordered',run:e=>{if(!e.isActive('orderedList'))e.chain().focus().toggleOrderedList().run()}},
  {id:'task-list',section:'基础块',name:'任务列表',copy:'可勾选任务',icon:'check-square',keywords:'任务 todo checklist',run:e=>{if(!e.isActive('taskList'))e.chain().focus().toggleTaskList().run()}},
  {id:'blockquote',section:'基础块',name:'引用',copy:'引用或强调内容',icon:'quote',keywords:'quote',run:e=>setTextBlock(e,'blockquote')},
  {id:'code-block',section:'基础块',name:'代码块',copy:'支持热门语言语法高亮',icon:'code',keywords:'代码 code js ts python java rust go',run:e=>setTextBlock(e,'codeBlock')},
  {id:'attachment',section:'媒体与高级内容',name:'图片或附件',copy:'保存到本机附件目录',icon:'paperclip',keywords:'图片 image file'},
  {id:'table',section:'媒体与高级内容',name:'表格',copy:'3 × 3 数据表格',icon:'table',keywords:'table 表'},
  {id:'math',section:'媒体与高级内容',name:'数学公式',copy:'支持 $ 行内与 $$ 块公式',icon:'code',keywords:'公式 math latex'},
  {id:'mermaid',section:'媒体与高级内容',name:'Mermaid 图',copy:'流程图、时序图与结构图',icon:'list-tree',keywords:'流程图 diagram'},
]
const textMatches=(editor:any,query:string):TextMatch[]=>{if(!query)return[];const matches:TextMatch[]=[];const needle=query.toLocaleLowerCase();editor.state.doc.descendants((node:any,pos:number)=>{if(!node.isText)return;const value=String(node.text??'').toLocaleLowerCase();let offset=0;while((offset=value.indexOf(needle,offset))>=0){matches.push({from:pos+offset,to:pos+offset+query.length});offset+=Math.max(1,query.length)}});return matches}

export function NoteEditor({note,availableTags,focusTitle=false,onChange,onTagsChange,onCreateTag,onAddAttachment}:Props){
  const titleRef=useRef<HTMLInputElement>(null);const fileRef=useRef<HTMLInputElement>(null);const slashRef=useRef<HTMLDivElement>(null);const findRef=useRef<HTMLInputElement>(null);const codeLanguageInputRef=useRef<HTMLInputElement>(null);const editorSurfaceRef=useRef<HTMLDivElement>(null);const activeCodeBlockRef=useRef('');const normalizedDocument=useMemo(()=>normalizeDocument(note.document),[note.id]);const latestTitle=useRef(note.title);const latestDocument=useRef(normalizedDocument)
  const [selection,setSelection]=useState<Point|null>(null);const [slash,setSlash]=useState<SlashState|null>(null);const [slashIndex,setSlashIndex]=useState(0);const [tableControl,setTableControl]=useState<Point|null>(null);const [codeControl,setCodeControl]=useState<(Point&{language:string;blockId:string})|null>(null);const [codeLanguageQuery,setCodeLanguageQuery]=useState('');const [codeSuggestionsOpen,setCodeSuggestionsOpen]=useState(false);const [codeLanguageIndex,setCodeLanguageIndex]=useState(0);const [findPanel,setFindPanel]=useState<FindPanel>(null);const [tagDraft,setTagDraft]=useState<string|null>(null);const [inputLayer,setInputLayer]=useState<InputLayer>(null)
  const filteredSlashItems=useMemo(()=>{const query=(slash?.query??'').trim().toLowerCase();return query?slashItems.filter(item=>`${item.name} ${item.copy} ${item.keywords??''}`.toLowerCase().includes(query)):slashItems},[slash?.query])
  const filteredCodeLanguages=useMemo(()=>{const query=codeLanguageQuery.trim().toLowerCase();return query?phycatCodeLanguages.filter(language=>(language||'auto').includes(query)):phycatCodeLanguages},[codeLanguageQuery])
  const codeLayerPoint=(box:DOMRect):Point|null=>{const bounds=editorSurfaceRef.current?.getBoundingClientRect();if(!bounds||box.bottom<bounds.top||box.bottom>bounds.bottom||box.right<bounds.left||box.left>bounds.right)return null;return{left:Math.max(bounds.left,Math.min(box.right-160,bounds.right-160)),top:box.bottom}}
  const updateLayers=(current:any)=>{const {from,to,$from}=current.state.selection;try{const start=current.view.coordsAtPos(from);const inCode=$from.parent.type.name==='codeBlock';if(from!==to&&!current.state.selection.node&&!inCode){const end=current.view.coordsAtPos(to);setSelection({left:start.left,top:Math.min(start.top,end.top)-8})}else setSelection(null);const before=$from.parent.type.name==='paragraph'?$from.parent.textBetween(0,$from.parentOffset,'\n','\0'):'';const slashMatch=from===to?before.match(/^\/(.*)$/):null;if(slashMatch){const origin=current.view.coordsAtPos($from.start());setSlash({left:origin.left,top:start.bottom+6,query:slashMatch[1]});setSlashIndex(0)}else setSlash(null);const domAt=current.view.domAtPos(from).node;const element=domAt instanceof Element?domAt:domAt.parentElement;const cell=element?.closest('td,th');if(cell){const box=cell.getBoundingClientRect();setTableControl({left:box.left,top:box.top})}else setTableControl(null);const topNode=$from.depth>=1?$from.node(1):current.state.selection.node;const topStart=$from.depth>=1?$from.before(1):from;const topDom=current.view.nodeDOM(topStart);const box=topDom instanceof HTMLElement?topDom.getBoundingClientRect():null;const point=box?codeLayerPoint(box):null;if(topNode?.type.name==='codeBlock'&&box&&point){const language=topNode.attrs.language??'';const blockId=topNode.attrs.blockId??'';if(activeCodeBlockRef.current!==blockId){activeCodeBlockRef.current=blockId;setCodeLanguageQuery(language);setCodeSuggestionsOpen(false);setCodeLanguageIndex(0)}setCodeControl({...point,language,blockId})}else{activeCodeBlockRef.current='';setCodeControl(null);setCodeLanguageQuery('');setCodeSuggestionsOpen(false)}}catch{activeCodeBlockRef.current='';setSelection(null);setSlash(null);setTableControl(null);setCodeControl(null);setCodeLanguageQuery('');setCodeSuggestionsOpen(false)}}
  const editor=useEditor({immediatelyRender:false,extensions:[StarterKit.configure({heading:{levels:[1,2,3,4,5]},link:false,underline:false,codeBlock:false}),PhycatCodeBlock,Underline,Highlight.configure({multicolor:false}),Link.configure({openOnClick:false,autolink:true,defaultProtocol:'https'}),Image.configure({allowBase64:true,inline:false}),TableKit.configure({table:{resizable:true}}),TaskList,TaskItem.configure({nested:true}),Mathematics.configure({katexOptions:{throwOnError:false}}),MarkdownMathShortcuts,MermaidNode,Placeholder.configure({placeholder:'输入 / 插入内容'}),StableBlockIds],content:toTiptapDocument(normalizedDocument),editorProps:{attributes:{class:'note-editor-content',role:'textbox','aria-label':'笔记正文','aria-multiline':'true'},handleKeyDown:(view,event)=>{if(event.key==='/'&&view.state.selection.empty&&view.state.selection.$from.parent.type.name==='paragraph'&&view.state.selection.$from.parent.textContent==='')window.setTimeout(()=>{const point=view.coordsAtPos(view.state.selection.from);setSlash({left:point.left,top:point.bottom+6,query:''});setSlashIndex(0)},0);return false}},onSelectionUpdate:({editor:current})=>updateLayers(current),onFocus:({editor:current})=>updateLayers(current),onBlur:()=>window.setTimeout(()=>setSelection(null),120),onUpdate:({editor:current})=>{const next=normalizeDocument({schemaVersion:1,type:'doc',content:current.getJSON().content??[]});latestDocument.current=next;onChange({title:latestTitle.current,documentJson:next});updateLayers(current)}})

  useEffect(()=>{latestTitle.current=note.title},[note.title]);useEffect(()=>{latestDocument.current=normalizedDocument;editor?.commands.setContent(toTiptapDocument(normalizedDocument),{emitUpdate:false})},[normalizedDocument,editor,note.id]);useEffect(()=>{if(focusTitle)titleRef.current?.focus()},[focusTitle,note.id])
  useEffect(()=>{if(!editor)return;const reposition=(event?:Event)=>{if(event?.type==='scroll'&&event.target instanceof Element&&event.target.closest('.slash-menu,.code-language-picker,.code-language-options'))return;if(editor.isFocused||activeCodeBlockRef.current)updateLayers(editor)};const viewport=window.visualViewport;const observer=new ResizeObserver(()=>reposition());observer.observe(editor.view.dom);window.addEventListener('resize',reposition);window.addEventListener('scroll',reposition,true);viewport?.addEventListener('resize',reposition);viewport?.addEventListener('scroll',reposition);return()=>{observer.disconnect();window.removeEventListener('resize',reposition);window.removeEventListener('scroll',reposition,true);viewport?.removeEventListener('resize',reposition);viewport?.removeEventListener('scroll',reposition)}},[editor])
  useEffect(()=>{if(!editor)return;const total=filteredSlashItems.length;const handler=(event:KeyboardEvent)=>{if(!slash)return;if(event.key==='ArrowDown'&&total){event.preventDefault();setSlashIndex(index=>(index+1)%total)}if(event.key==='ArrowUp'&&total){event.preventDefault();setSlashIndex(index=>(index-1+total)%total)}if(event.key==='Enter'&&total){event.preventDefault();runSlash(filteredSlashItems[Math.min(slashIndex,total-1)])}if(event.key==='Escape')setSlash(null)};document.addEventListener('keydown',handler,true);return()=>document.removeEventListener('keydown',handler,true)},[editor,slash,slashIndex,filteredSlashItems])
  useEffect(()=>{if(!editor)return;const handler=(event:KeyboardEvent)=>{if(!(event.ctrlKey||event.metaKey)||event.altKey)return;const key=event.key.toLowerCase();const editing=editor.isFocused||editor.view.dom.contains(event.target as globalThis.Node);if(!editing)return;if(/^[1-6]$/.test(key)){event.preventDefault();const level=Number(key);if(level<=5)editor.chain().focus().setHeading({level:level as 1|2|3|4|5}).run();else editor.chain().focus().setParagraph().run();return}if(key==='i'){event.preventDefault();editor.chain().focus().toggleItalic().run()}else if(key==='u'){event.preventDefault();editor.chain().focus().toggleUnderline().run()}else if(key==='t'){event.preventDefault();editor.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:true}).run()}else if(key==='f'||key==='h'){event.preventDefault();setFindPanel(current=>({replace:key==='h',query:current?.query??'',replacement:current?.replacement??'',index:-1}));window.setTimeout(()=>findRef.current?.focus(),0)}};document.addEventListener('keydown',handler,true);return()=>document.removeEventListener('keydown',handler,true)},[editor])
  useEffect(()=>{slashRef.current?.querySelector('.slash-item.active')?.scrollIntoView({block:'nearest'})},[slashIndex])
  if(!editor)return null

  const addFile=async(file:File)=>{const url=await onAddAttachment(file);if(file.type.startsWith('image/'))editor.chain().focus().setImage({src:url,alt:file.name,title:file.name}).run();else editor.chain().focus().insertContent(`<p><a href="${url}" download="${file.name}">${file.name}</a></p>`).run()}
  function runSlash(item:SlashItem){if(!editor)return;const {from,$from}=editor.state.selection;editor.chain().focus().deleteRange({from:$from.start(),to:from}).run();if(item.run)item.run(editor);else if(item.id==='attachment')fileRef.current?.click();else if(item.id==='table')editor.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:true}).run();else if(item.id==='math')setInputLayer({kind:'blockMath',value:'\\sum_{i=1}^{n} i'});else if(item.id==='mermaid')setInputLayer({kind:'mermaid',value:'graph TD\n  A[开始] --> B[完成]'});setSlash(null)}
  const applyInput=async()=>{if(!inputLayer)return;const value=inputLayer.value.trim();if(!value){setInputLayer(null);return}if(inputLayer.kind==='link')editor.chain().focus().extendMarkRange('link').setLink({href:value}).run();if(inputLayer.kind==='inlineMath')editor.chain().focus().insertInlineMath({latex:value}).run();if(inputLayer.kind==='blockMath')editor.chain().focus().insertBlockMath({latex:value}).run();if(inputLayer.kind==='mermaid')editor.chain().focus().insertContent({type:'mermaid',attrs:{source:value}}).run();if(inputLayer.kind==='tag'){const existing=availableTags.find(tag=>tag.name.toLowerCase()===value.toLowerCase());const tag=existing??await onCreateTag(value);onTagsChange([...note.tags.map(x=>x.id),tag.id])}setInputLayer(null)}
  const commitTag=async()=>{if(tagDraft===null)return;const value=tagDraft.trim();setTagDraft(null);if(!value)return;const existing=availableTags.find(tag=>tag.name.toLowerCase()===value.toLowerCase());const tag=existing??await onCreateTag(value);if(!note.tags.some(item=>item.id===tag.id))onTagsChange([...note.tags.map(item=>item.id),tag.id])}
  const revealMatch=(direction:1|-1=1)=>{if(!findPanel?.query)return;const matches=textMatches(editor,findPanel.query);if(!matches.length){setFindPanel({...findPanel,index:-1});return}const next=findPanel.index<0?(direction===1?0:matches.length-1):(findPanel.index+direction+matches.length)%matches.length;const match=matches[next];editor.view.dispatch(editor.state.tr.setSelection(TextSelection.create(editor.state.doc,match.from,match.to)).scrollIntoView());setFindPanel({...findPanel,index:next})}
  const replaceCurrent=()=>{if(!findPanel?.query)return;const matches=textMatches(editor,findPanel.query);const index=Math.max(0,Math.min(findPanel.index,matches.length-1));const match=matches[index];if(!match)return;editor.view.dispatch(editor.state.tr.insertText(findPanel.replacement,match.from,match.to));setFindPanel({...findPanel,index:Math.min(index,Math.max(0,matches.length-2))})}
  const replaceAll=()=>{if(!findPanel?.query)return;const matches=textMatches(editor,findPanel.query);let transaction=editor.state.tr;for(const match of [...matches].reverse())transaction=transaction.insertText(findPanel.replacement,match.from,match.to);if(matches.length)editor.view.dispatch(transaction);setFindPanel({...findPanel,index:0})}
  const chooseCodeLanguage=(language:string)=>{if(!codeControl)return;const normalized=language.trim().toLowerCase();let position:number|null=null;let attrs:any=null;editor.state.doc.descendants((node:any,pos:number)=>{if(position===null&&node.type.name==='codeBlock'&&node.attrs.blockId===codeControl.blockId){position=pos;attrs=node.attrs;return false}});if(position!==null)editor.view.dispatch(editor.state.tr.setNodeMarkup(position,undefined,{...attrs,language:normalized||null}));setCodeControl({...codeControl,language:normalized});setCodeLanguageQuery(normalized);setCodeSuggestionsOpen(false);setCodeLanguageIndex(0)}
  const codeLayerBounds=editorSurfaceRef.current?.getBoundingClientRect()
  const codeSuggestionsAbove=!!codeControl&&!!codeLayerBounds&&codeControl.top+Math.min(320,filteredCodeLanguages.length*34+12)+32>codeLayerBounds.bottom
  const codeOptionsMaxHeight=codeControl&&codeLayerBounds?Math.max(40,Math.min(320,codeSuggestionsAbove?codeControl.top-codeLayerBounds.top-5:codeLayerBounds.bottom-codeControl.top-32)):320

  return <div className="document-body">
    <div className="document-heading"><input ref={titleRef} className="document-title-input" aria-label="笔记标题" value={note.title} placeholder="无标题笔记" onChange={event=>{latestTitle.current=event.target.value;onChange({title:event.target.value,documentJson:latestDocument.current})}}/><div className="document-tags" id="documentTags"><span className="document-chip">自动保存 · 本机笔记</span>{note.tags.map(tag=><button className="tag removable" key={tag.id} onClick={()=>onTagsChange(note.tags.filter(x=>x.id!==tag.id).map(x=>x.id))}>{tag.name}<Icon name="x"/></button>)}{tagDraft===null?<button className="document-chip add-tag" id="addTag" onClick={()=>setTagDraft('')}><Icon name="plus"/>添加标签</button>:<label className="inline-tag-editor"><input autoFocus aria-label="输入标签" placeholder="输入标签名称" value={tagDraft} onChange={event=>setTagDraft(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();void commitTag()}if(event.key==='Escape')setTagDraft(null)}} onBlur={()=>void commitTag()} list="availableTags"/><datalist id="availableTags">{availableTags.filter(tag=>!note.tags.some(item=>item.id===tag.id)).map(tag=><option key={tag.id} value={tag.name}/>)}</datalist></label>}</div></div>
    <div ref={editorSurfaceRef} className="editor-surface" onPointerDownCapture={event=>{const target=event.target instanceof Element?event.target:null;const block=target?.closest<HTMLElement>('pre.phycat-code');if(!block||!event.currentTarget.contains(block))return;const box=block.getBoundingClientRect();const point=codeLayerPoint(box);if(!point){activeCodeBlockRef.current='';setCodeControl(null);return}const language=block.dataset.language??'';const blockId=block.dataset.blockId??'';if(activeCodeBlockRef.current!==blockId){activeCodeBlockRef.current=blockId;setCodeLanguageQuery(language);setCodeSuggestionsOpen(false);setCodeLanguageIndex(0)}setSelection(null);setCodeControl({...point,language,blockId})}}><EditorContent editor={editor}/></div>
    <FloatingLayer open={!!selection} point={selection??undefined} placement="top-start" gap={8} className="selection-toolbar product-layer" onDismiss={()=>setSelection(null)}>{selection&&<div className="selection-toolbar-inner" onMouseDown={event=>event.preventDefault()}>{([1,2,3,4,5] as const).map(level=><button key={level} className={`heading-tool${editor.isActive('heading',{level})?' active':''}`} title={`${level} 级标题`} onClick={()=>editor.chain().focus().toggleHeading({level}).run()}>H{level}</button>)}<span className="divider"/><button className={editor.isActive('bold')?'active':''} onClick={()=>editor.chain().focus().toggleBold().run()}><strong>B</strong></button><button onClick={()=>editor.chain().focus().toggleItalic().run()}><i>I</i></button><button onClick={()=>editor.chain().focus().toggleUnderline().run()}><u>U</u></button><button onClick={()=>editor.chain().focus().toggleStrike().run()}><s>S</s></button><button onClick={()=>editor.chain().focus().toggleCode().run()}><Icon name="code"/></button><span className="divider"/><button onClick={()=>setInputLayer({kind:'link',value:editor.getAttributes('link').href??'https://'})}><Icon name="link"/></button></div>}</FloatingLayer>
    <FloatingLayer open={!!slash} point={slash??undefined} placement="bottom-start" gap={4} className="slash-menu product-layer" onDismiss={()=>setSlash(null)}>{slash&&<div className="slash-menu-scroll"><div className="slash-search"><Icon name="search"/><span>{slash.query?`搜索：${slash.query}`:'输入关键词筛选，Enter 使用'}</span></div><div ref={slashRef} className="slash-menu-items">{(['基础块','媒体与高级内容'] as const).map(section=>{const items=filteredSlashItems.filter(item=>item.section===section);return items.length?<div className="slash-section" key={section}><div className="slash-label">{section}</div>{items.map(item=>{const index=filteredSlashItems.indexOf(item);return <button className={`slash-item${index===slashIndex?' active':''}`} key={item.id} onMouseDown={event=>event.preventDefault()} onMouseEnter={()=>setSlashIndex(index)} onClick={()=>runSlash(item)}>{item.badge?<span className="slash-type-badge">{item.badge}</span>:<Icon name={item.icon??'file-text'}/>}<span className="slash-copy"><strong>{item.name}</strong><small>{item.copy}</small></span></button>})}</div>:null})}{!filteredSlashItems.length&&<div className="slash-empty">没有匹配的内容块</div>}</div></div>}</FloatingLayer>
    <FloatingLayer open={!!tableControl} point={tableControl??undefined} placement="top-start" gap={8} className="table-toolbar product-layer" onDismiss={()=>setTableControl(null)}>{tableControl&&<div onMouseDown={event=>event.preventDefault()}><button title="向上插入行" onClick={()=>editor.chain().focus().addRowBefore().run()}><Icon name="plus"/>上方行</button><button title="向下插入行" onClick={()=>editor.chain().focus().addRowAfter().run()}><Icon name="plus"/>下方行</button><button title="向左插入列" onClick={()=>editor.chain().focus().addColumnBefore().run()}><Icon name="columns-2"/>左侧列</button><button title="向右插入列" onClick={()=>editor.chain().focus().addColumnAfter().run()}><Icon name="columns-2"/>右侧列</button><span className="divider"/><button className="danger" title="删除当前行" onClick={()=>editor.chain().focus().deleteRow().run()}><Icon name="trash-2"/>行</button><button className="danger" title="删除当前列" onClick={()=>editor.chain().focus().deleteColumn().run()}><Icon name="trash-2"/>列</button><button className="danger" title="删除表格" onClick={()=>editor.chain().focus().deleteTable().run()}><Icon name="trash-2"/>表格</button></div>}</FloatingLayer>
    <FloatingLayer open={!!codeControl} boundary={editorSurfaceRef} point={codeControl??undefined} placement="bottom-start" gap={0} className={`code-language-picker${codeSuggestionsOpen?' suggestions-open':''}${codeSuggestionsAbove?' suggestions-above':''}`} onDismiss={()=>{activeCodeBlockRef.current='';setCodeControl(null);setCodeLanguageQuery('');setCodeSuggestionsOpen(false)}}>{codeControl&&<div className="code-language-control"><input ref={codeLanguageInputRef} aria-label="搜索代码语言" placeholder="代码语言" spellCheck={false} autoCapitalize="none" autoCorrect="off" value={codeLanguageQuery} onFocus={event=>{const input=event.currentTarget;setCodeLanguageQuery(codeControl.language);setCodeSuggestionsOpen(true);setCodeLanguageIndex(Math.max(0,phycatCodeLanguages.indexOf(codeControl.language)));window.setTimeout(()=>input.select(),0)}} onChange={event=>{setCodeLanguageQuery(event.target.value.toLowerCase());setCodeSuggestionsOpen(true);setCodeLanguageIndex(0)}} onBlur={()=>window.setTimeout(()=>{if(!document.activeElement?.closest('.code-language-picker'))chooseCodeLanguage(codeLanguageQuery)},0)} onKeyDown={event=>{const total=filteredCodeLanguages.length;if(event.key==='ArrowDown'&&total){event.preventDefault();setCodeSuggestionsOpen(true);setCodeLanguageIndex(index=>(index+1)%total)}else if(event.key==='ArrowUp'&&total){event.preventDefault();setCodeSuggestionsOpen(true);setCodeLanguageIndex(index=>(index-1+total)%total)}else if(event.key==='Enter'){event.preventDefault();chooseCodeLanguage(codeSuggestionsOpen&&total?filteredCodeLanguages[Math.min(codeLanguageIndex,total-1)]:codeLanguageQuery);editor.commands.focus()}else if(event.key==='Escape'){event.preventDefault();event.stopPropagation();setCodeLanguageQuery(codeControl.language);setCodeSuggestionsOpen(false);editor.commands.focus()}}}/>{codeSuggestionsOpen&&<ul className="code-language-options" role="listbox" style={{maxHeight:codeOptionsMaxHeight}}>{filteredCodeLanguages.map((language,index)=><li key={language||'auto'}><button type="button" role="option" aria-selected={codeControl.language===language} className={`${index===codeLanguageIndex?'active ':''}${codeControl.language===language?'selected ':''}${language?'':'is-auto'}`} onMouseDown={event=>event.preventDefault()} onMouseEnter={()=>setCodeLanguageIndex(index)} onClick={()=>{chooseCodeLanguage(language);editor.commands.focus()}}><CodeLanguageIcon language={language}/><span className="code-language-label">{language||'auto'}</span></button></li>)}</ul>}</div>}</FloatingLayer>
    {findPanel&&createPortal(<div className="editor-find-bar product-layer" role="search"><label><Icon name="search"/><input ref={findRef} aria-label="查找内容" placeholder="查找" value={findPanel.query} onChange={event=>setFindPanel({...findPanel,query:event.target.value,index:-1})} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();revealMatch(event.shiftKey?-1:1)}if(event.key==='Escape')setFindPanel(null)}}/></label>{findPanel.replace&&<input aria-label="替换为" placeholder="替换为" value={findPanel.replacement} onChange={event=>setFindPanel({...findPanel,replacement:event.target.value})} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();replaceCurrent()}if(event.key==='Escape')setFindPanel(null)}}/>}<span className="find-count">{findPanel.query?`${Math.min(Math.max(0,findPanel.index+1),textMatches(editor,findPanel.query).length)}/${textMatches(editor,findPanel.query).length}`:'0/0'}</span><button aria-label="上一个" onClick={()=>revealMatch(-1)}><Icon name="arrow-up"/></button><button aria-label="下一个" onClick={()=>revealMatch(1)}><Icon name="arrow-down"/></button>{findPanel.replace&&<><button className="find-text-action" onClick={replaceCurrent}>替换</button><button className="find-text-action" onClick={replaceAll}>全部替换</button></>}<button aria-label="关闭查找" onClick={()=>setFindPanel(null)}><Icon name="x"/></button></div>,document.body)}
    {inputLayer&&<div className={`inline-input-popover product-layer${inputLayer.kind==='mermaid'?' is-mermaid':''}`}>{inputLayer.kind==='mermaid'?<textarea autoFocus aria-label="输入 Mermaid 源码" value={inputLayer.value} onChange={event=>setInputLayer({...inputLayer,value:event.target.value})} onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();void applyInput()}if(event.key==='Escape')setInputLayer(null)}}/>:<input autoFocus aria-label="输入内容" placeholder={inputLayer.kind==='link'?'输入链接地址':inputLayer.kind==='tag'?'输入标签名称':'输入 LaTeX 公式'} value={inputLayer.value} onChange={event=>setInputLayer({...inputLayer,value:event.target.value})} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();void applyInput()}if(event.key==='Escape')setInputLayer(null)}}/>}<button onClick={()=>void applyInput()}>确认</button></div>}
    <input ref={fileRef} hidden type="file" onChange={event=>{const file=event.target.files?.[0];if(file)void addFile(file);event.target.value=''}}/>
  </div>
}
