import type { AttachmentDto, CategoryDto, GalleryAssetDataDto, GalleryItemDto, GallerySummaryDto, GalleryTransferResultDto, JottingDto, JottingFolderDto, JottingSnapshotDto, LibraryDto, NoteDto, NoteQuery, Page, SaveNoteRequest, SaveNoteResult, WorkspaceSnapshotDto, BatchAction, VersionedDocument, SearchResultDto } from './contracts'

const KEY = 'coolnote-web-store-v1'
const uncategorized = '00000000-0000-4000-8000-000000000001'
type State = { library: LibraryDto; categories: CategoryDto[]; notes: NoteDto[]; attachments: AttachmentDto[]; jottingFolders:JottingFolderDto[]; jottings:JottingDto[]; galleries:GallerySummaryDto[]; galleryItems:GalleryItemDto[] }
const now = () => new Date().toISOString()
const emptyDoc = (): VersionedDocument => ({ schemaVersion: 1, type: 'doc', content: [{ type: 'paragraph', attrs: { blockId: crypto.randomUUID() }, content: [] }] })
const load = (): State => {
  try { const raw = localStorage.getItem(KEY); if (raw) return JSON.parse(raw) } catch { /* reset corrupted browser data */ }
  const stamp = now(); return { library: { id: crypto.randomUUID(), name: 'CoolNote Web', rootPath: 'browser://localStorage', formatVersion: 1, createdAt: stamp, lastOpenedAt: stamp, lastCleanShutdownAt: null, settingsJson: '{}', settingsRevision: 1 }, categories: [{ id: uncategorized, parentId: null, name: '未分类', iconName: 'folder', color: '#1687e8', sortOrder: 0, noteCount: 0 }], notes: [], attachments: [], jottingFolders:[], jottings:[], galleries:[], galleryItems:[] }
}
let state = load()
state.attachments ??= []
state.jottingFolders ??= []
state.jottings ??= []
state.galleries ??= []
state.galleryItems ??= []
state.notes = state.notes.map(note=>({...note,mood:note.mood??null}))
state.categories = state.categories.map(category => ({ id:category.id,parentId:null,name:category.name,iconName:category.iconName,color:category.color,sortOrder:category.sortOrder,noteCount:category.noteCount }))
const persist = () => localStorage.setItem(KEY, JSON.stringify(state))
const plain = (doc: VersionedDocument) => { const visit=(nodes:VersionedDocument['content']):string=>nodes.map(n=>n.text??(n.content?visit(n.content):'')).join(' '); return visit(doc.content).replace(/\s+/g,' ').trim() }
const touchCounts = () => state.categories = state.categories.map(c => ({ ...c, noteCount: state.notes.filter(n => n.categoryId === c.id && !n.deletedAt).length }))
export const webInitialize = () => { state.library.lastOpenedAt = now(); touchCounts(); persist(); return state.library }
export const webSnapshot = (): WorkspaceSnapshotDto => { touchCounts(); return { categories: [...state.categories].sort((a,b)=>a.sortOrder-b.sortOrder), systemCounts:{all:state.notes.filter(n=>!n.deletedAt&&!n.isArchived).length,favorites:state.notes.filter(n=>!n.deletedAt&&!n.isArchived&&n.isFavorite).length,archived:state.notes.filter(n=>!n.deletedAt&&n.isArchived).length,trash:state.notes.filter(n=>!!n.deletedAt).length,jottings:state.jottings.length,galleries:state.galleries.length} } }
export const webQuery = (q: NoteQuery): Page<any> => { let rows = state.notes.filter(n => q.view === 'trash' ? !!n.deletedAt : !n.deletedAt && (q.view === 'favorites' ? n.isFavorite && !n.isArchived : q.view === 'archived' ? n.isArchived : true)); if (q.categoryId) rows = rows.filter(n => n.categoryId === q.categoryId); if (q.search?.trim()) { const s = q.search.toLowerCase(); rows = rows.filter(n => `${n.title} ${n.plainText}`.toLowerCase().includes(s)) } rows.sort((a,b) => { const av=q.sortBy==='title'?a.title.toLowerCase():q.sortBy==='createdAt'?a.createdAt:a.updatedAt; const bv=q.sortBy==='title'?b.title.toLowerCase():q.sortBy==='createdAt'?b.createdAt:b.updatedAt; return (q.sortDirection==='asc'?1:-1)*(av< bv?-1:av>bv?1:0) }); return { total: rows.length, items: rows.slice(q.offset, q.offset+q.limit).map(n => ({ ...n, excerpt: n.plainText })) } }
export const webGet = (id: string) => state.notes.find(n => n.id === id) ?? (() => { throw new Error('笔记不存在') })()
export const webCreate = (categoryId?: string | null) => { const stamp=now(); const doc=emptyDoc(); const n:NoteDto={id:crypto.randomUUID(),categoryId:categoryId||uncategorized,title:'',document:doc,plainText:'',contentHash:'',revision:1,isFavorite:false,isArchived:false,deletedAt:null,mood:null,createdAt:stamp,updatedAt:stamp}; state.notes.unshift(n); touchCounts(); persist(); return n }
export const webSave = (r: SaveNoteRequest): SaveNoteResult => { const n=webGet(r.noteId); if (n.revision !== r.baseRevision) throw new Error('笔记已被其他编辑器更新'); n.title=r.title; n.document=r.documentJson as VersionedDocument; n.plainText=plain(n.document); n.revision++; n.updatedAt=now(); persist(); return { noteId:n.id, revision:n.revision, updatedAt:n.updatedAt, contentHash:'' } }
export const webBatch = (ids:string[], action:BatchAction) => { const stamp=now(); for(const n of state.notes.filter(n=>ids.includes(n.id))){ if(action==='favorite'&&!n.deletedAt)n.isFavorite=true; if(action==='unfavorite')n.isFavorite=false; if(action==='archive')n.isArchived=true; if(action==='unarchive')n.isArchived=false; if(action==='trash'){n.deletedAt=stamp;n.isFavorite=false} if(action==='restore')n.deletedAt=null; if(action==='deletePermanently')state.notes=state.notes.filter(x=>x.id!==n.id) } touchCounts(); persist(); return ids.length }
export const webEmptyTrash=()=>{const before=state.notes.length;state.notes=state.notes.filter(note=>!note.deletedAt);touchCounts();persist();return before-state.notes.length}
export const webMove = (ids:string[], categoryId:string) => { state.notes.filter(n=>ids.includes(n.id)).forEach(n=>n.categoryId=categoryId); persist(); return ids.length }
export const webCreateCategory = (name:string,_parentId?:string|null) => { const c:CategoryDto={id:crypto.randomUUID(),parentId:null,name,iconName:'folder',color:'#1687e8',sortOrder:state.categories.length,noteCount:0}; state.categories.push(c); persist(); return c }
export const webRenameCategory=(id:string,name:string)=>{const c=state.categories.find(c=>c.id===id);if(c)c.name=name;persist()}
export const webDeleteCategory=(id:string)=>{state.notes.filter(n=>n.categoryId===id).forEach(n=>n.categoryId=uncategorized);state.categories=state.categories.filter(c=>c.id!==id);touchCounts();persist()}
export const webUpdateCategoryAppearance=(id:string,iconName:string,color:string)=>{const c=state.categories.find(c=>c.id===id);if(c){c.iconName=iconName;c.color=color}persist()}
export const webSetMood=(id:string,mood:string|null)=>{const note=state.notes.find(item=>item.id===id);if(note){note.mood=mood;note.updatedAt=now()}persist()}
export const webGlobalSearch=(query:string,limit:number):SearchResultDto[]=>{const needle=query.trim().toLowerCase();if(!needle)return[];return [...state.notes.filter(n=>!n.deletedAt&&`${n.title} ${n.plainText}`.toLowerCase().includes(needle)).map(n=>({id:n.id,kind:'note' as const,title:n.title||'无标题笔记',excerpt:n.plainText,updatedAt:n.updatedAt})),...state.jottings.filter(n=>`${n.name} ${n.content}`.toLowerCase().includes(needle)).map(n=>({id:n.id,kind:'jotting' as const,title:n.name,excerpt:n.content.replace(/<[^>]+>/g,' '),updatedAt:n.updatedAt})),...state.galleries.filter(n=>`${n.name} ${n.introduction}`.toLowerCase().includes(needle)).map(n=>({id:n.id,kind:'gallery' as const,title:n.name,excerpt:n.introduction,updatedAt:n.updatedAt}))].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,limit)}
export const webSaveAttachment=(noteId:string,fileName:string,mediaType:string,dataBase64:string)=>{const contentHash=`${dataBase64.length}:${dataBase64.slice(0,32)}:${dataBase64.slice(-32)}`;const existing=state.attachments.find(item=>item.contentHash===contentHash);const item:AttachmentDto={id:crypto.randomUUID(),noteId,fileName,mediaType,sizeBytes:Math.floor(dataBase64.length*0.75),contentHash,dataUrl:existing?.dataUrl??`data:${mediaType};base64,${dataBase64}`,createdAt:now()};state.attachments.push(item);persist();return item}
export const webListAttachments=(noteId:string)=>state.attachments.filter(item=>item.noteId===noteId)
export const webDeleteAttachment=(id:string)=>{state.attachments=state.attachments.filter(item=>item.id!==id);persist()}
export const webExport=(ids:string[],format:string)=>state.notes.filter(n=>ids.includes(n.id)).map(n=>format==='json'?n:format==='html'?`<article><h1>${n.title}</h1><p>${n.plainText}</p></article>`:`# ${n.title}\n\n${n.plainText}`).map(v=>typeof v==='string'?v:JSON.stringify(v)).join(format==='json'?'\n': '\n\n---\n\n')
export const webImport=(content:string,format:string,categoryId?:string|null,parsed?:{title:string;document:VersionedDocument})=>{const title=parsed?.title??(format==='markdown'?(content.match(/^#\s*(.*)$/m)?.[1]||'导入笔记'):'导入笔记'); return [webCreate(categoryId)].map(n=>{n.title=title;n.document=parsed?.document??{schemaVersion:1,type:'doc',content:[{type:'paragraph',attrs:{blockId:crypto.randomUUID()},content:[{type:'text',text:content}]}]};n.plainText=plain(n.document);persist();return n})}
export const webJottingSnapshot=():JottingSnapshotDto=>({folders:state.jottingFolders,jottings:state.jottings})
export const webCreateJottingFolder=(name:string,parentId?:string|null)=>{const item:JottingFolderDto={id:crypto.randomUUID(),parentId:parentId??null,name,sortOrder:state.jottingFolders.length};state.jottingFolders.push(item);persist();return item}
export const webCreateJotting=(name:string,folderId?:string|null)=>{const stamp=now();const item:JottingDto={id:crypto.randomUUID(),folderId:folderId??null,name,content:'<h1>无标题</h1><p><br></p>',cover:null,isFavorite:false,sortOrder:state.jottings.length,revision:1,createdAt:stamp,updatedAt:stamp};state.jottings.push(item);persist();return item}
export const webUpdateJotting=(id:string,baseRevision:number,name:string,content:string,cover:string|null,isFavorite:boolean)=>{const item=state.jottings.find(x=>x.id===id);if(!item)throw new Error('小记不存在');if(item.revision!==baseRevision)throw new Error('小记已被更新');item.name=name;item.content=content;item.cover=cover;item.isFavorite=isFavorite;item.revision++;item.updatedAt=now();persist();return item}
export const webMoveJotting=(id:string,folderId?:string|null)=>{const item=state.jottings.find(x=>x.id===id);if(!item)throw new Error('小记不存在');if(folderId&&!state.jottingFolders.some(x=>x.id===folderId))throw new Error('目标文件夹不存在');item.folderId=folderId??null;item.updatedAt=now();persist();return item}
export const webDeleteJotting=(id:string)=>{state.jottings=state.jottings.filter(x=>x.id!==id);persist()}
export const webDeleteJottingFolder=(id:string)=>{state.jottingFolders=state.jottingFolders.filter(x=>x.id!==id);state.jottings.forEach(x=>{if(x.folderId===id)x.folderId=null});persist()}
export const webListGalleries=()=>[...state.galleries].sort((a,b)=>a.sortOrder-b.sortOrder)
export const webCreateGallery=(name:string)=>{const stamp=now();const item:GallerySummaryDto={id:crypto.randomUUID(),name:name.trim(),introduction:'',cover:null,sortOrder:state.galleries.length,revision:1,itemCount:0,createdAt:stamp,updatedAt:stamp};state.galleries.push(item);persist();return item}
export const webUpdateGallery=(id:string,baseRevision:number,name:string,introduction:string,cover:string|null)=>{const item=state.galleries.find(x=>x.id===id);if(!item)throw new Error('画廊不存在');if(item.revision!==baseRevision)throw new Error('画廊已被更新');item.name=name.trim();item.introduction=introduction;item.cover=cover;item.revision++;item.updatedAt=now();persist();return item}
const reorder=<T extends {id:string;sortOrder:number}>(values:T[],id:string,beforeId?:string|null)=>{const index=values.findIndex(x=>x.id===id);if(index<0)return;const [item]=values.splice(index,1);const target=beforeId?values.findIndex(x=>x.id===beforeId):-1;values.splice(target<0?values.length:target,0,item);values.forEach((x,i)=>x.sortOrder=i)}
export const webReorderGallery=(id:string,beforeId?:string|null)=>{reorder(state.galleries,id,beforeId);persist()}
export const webListGalleryItems=(galleryId:string,offset:number,limit:number):Page<GalleryItemDto>=>{const rows=state.galleryItems.filter(x=>x.galleryId===galleryId).sort((a,b)=>a.sortOrder-b.sortOrder);return{total:rows.length,items:rows.slice(offset,offset+limit)}}
export const webReorderGalleryItem=(galleryId:string,itemId:string,beforeId?:string|null)=>{reorder(state.galleryItems.filter(x=>x.galleryId===galleryId),itemId,beforeId);persist()}
const deleted=new Map<string,{galleries:GallerySummaryDto[];items:GalleryItemDto[]}>()
export const webDeleteGallery=(id:string)=>{const token=crypto.randomUUID();const galleries=state.galleries.filter(x=>x.id===id);const items=state.galleryItems.filter(x=>x.galleryId===id);deleted.set(token,{galleries,items});state.galleries=state.galleries.filter(x=>x.id!==id);state.galleryItems=state.galleryItems.filter(x=>x.galleryId!==id);persist();return token}
export const webDeleteGalleryItems=(ids:string[])=>{const token=crypto.randomUUID();const items=state.galleryItems.filter(x=>ids.includes(x.id));deleted.set(token,{galleries:[],items});state.galleryItems=state.galleryItems.filter(x=>!ids.includes(x.id));persist();return token}
export const webUndoGalleryDelete=(token:string)=>{const value=deleted.get(token);if(!value)return false;state.galleries.push(...value.galleries);state.galleryItems.push(...value.items);deleted.delete(token);persist();return true}
export const webTransferGalleryItems=(ids:string[],targetGalleryId:string,moveItems:boolean):GalleryTransferResultDto=>{let changed=0,skipped=0;for(const source of state.galleryItems.filter(x=>ids.includes(x.id))){if(state.galleryItems.some(x=>x.galleryId===targetGalleryId&&x.assetId===source.assetId)){skipped++;continue}state.galleryItems.push({...source,id:crypto.randomUUID(),galleryId:targetGalleryId,sortOrder:state.galleryItems.filter(x=>x.galleryId===targetGalleryId).length});if(moveItems)state.galleryItems=state.galleryItems.filter(x=>x.id!==source.id);changed++}persist();return{changed,skipped}}
export const webGetGalleryAssetData=(itemId:string):GalleryAssetDataDto=>{const item=state.galleryItems.find(x=>x.id===itemId);if(!item?.thumbnailDataUrl)throw new Error('Web 模式没有原图数据');return{fileName:item.originalFileName,mediaType:item.mediaType,dataUrl:item.thumbnailDataUrl}}
