import Link from '@tiptap/extension-link'
import type { Editor } from '@tiptap/core'
import Underline from '@tiptap/extension-underline'
import { EditorContent, useEditor } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import { useEffect, useRef, useState } from 'react'

import { Icon } from '../../shared/components/Icon'
import { FloatingLayer } from '../../shared/components/Overlay'
import { createJotting, createJottingFolder, deleteJotting, deleteJottingFolder, getJottingSnapshot, moveJotting, updateJotting } from '../../shared/tauri/commands'
import type { JottingDto, JottingFolderDto } from '../../shared/tauri/contracts'

type Props={collapsed:boolean;onToggle:()=>void;onToast:(message:string)=>void;onError:(message:string)=>void}
type Draft={kind:'file'|'folder';folderId:string|null;value:string}
const covers=['./assets/jotting-cover-sky.svg','./assets/jotting-cover-forest.svg','./assets/jotting-cover-dusk.svg']
const defaultContent='<h1>无标题</h1><p><em>从此刻开始，写下一则小记。</em></p><p><br></p>'
const fileData=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})
const titleFromName=(name:string)=>name.replace(/\.md$/i,'').trim()||'无标题'
const nameFromTitle=(title:string)=>`${(title.replace(/[\\/:*?"<>|]/g,'-').trim()||'无标题')}.md`
const syncFirstHeading=(editor:Editor|null,name:string)=>{if(!editor)return false;const json=editor.getJSON() as any;const first=json.content?.[0];const title=titleFromName(name);if(first?.type==='heading'&&first.attrs?.level===1){const current=first.content?.map((node:any)=>node.text??'').join('')??'';if(current===title)return false;first.content=[{type:'text',text:title}]}else json.content=[{type:'heading',attrs:{level:1},content:[{type:'text',text:title}]},...(json.content??[])];editor.commands.setContent(json,{emitUpdate:false});return true}

export function JottingsWorkspace({collapsed,onToggle,onToast,onError}:Props){
  const [folders,setFolders]=useState<JottingFolderDto[]>([]);const [items,setItems]=useState<JottingDto[]>([])
  const [selectedId,setSelectedId]=useState<string|null>(null);const [expanded,setExpanded]=useState<Set<string>>(new Set())
  const [draft,setDraft]=useState<Draft|null>(null);const [renamingId,setRenamingId]=useState<string|null>(null);const [renameValue,setRenameValue]=useState('');const [createMenu,setCreateMenu]=useState(false);const [coverMenu,setCoverMenu]=useState(false);const [moreMenu,setMoreMenu]=useState(false);const [deleteConfirm,setDeleteConfirm]=useState<string|null>(null);const [draggingId,setDraggingId]=useState<string|null>(null);const [dropFolderId,setDropFolderId]=useState<string|null|undefined>(undefined)
  const [content,setContent]=useState(defaultContent);const [name,setName]=useState('未命名小记.md');const [cover,setCover]=useState<string|null>(null);const [favorite,setFavorite]=useState(false);const [saveState,setSaveState]=useState('已保存')
  const dirty=useRef(false);const uploadRef=useRef<HTMLInputElement>(null);const createButtonRef=useRef<HTMLButtonElement>(null);const coverButtonRef=useRef<HTMLButtonElement>(null);const moreButtonRef=useRef<HTMLButtonElement>(null);const current=items.find(item=>item.id===selectedId)??null
  const currentFolder=current?.folderId?folders.find(folder=>folder.id===current.folderId)??null:null
  const editor=useEditor({immediatelyRender:false,extensions:[StarterKit,Underline,Link.configure({openOnClick:false,autolink:true})],content,editorProps:{attributes:{class:'jotting-markdown','aria-label':'小记 Markdown 正文'}},onUpdate:({editor:active})=>{dirty.current=true;setContent(active.getHTML());const first=(active.getJSON() as any).content?.[0];if(first?.type==='heading'&&first.attrs?.level===1){const nextName=nameFromTitle(first.content?.map((node:any)=>node.text??'').join('')??'');setName(nextName);if(selectedId)setItems(values=>values.map(value=>value.id===selectedId?{...value,name:nextName}:value))}}})
  useEffect(()=>{void getJottingSnapshot().then(snapshot=>{setFolders(snapshot.folders);setItems(snapshot.jottings.map(item=>({...item,isFavorite:item.isFavorite??false})));setExpanded(new Set(snapshot.folders.map(x=>x.id)));if(snapshot.jottings[0])setSelectedId(snapshot.jottings[0].id)}).catch(cause=>onError(cause instanceof Error?cause.message:'无法打开小记'))},[onError])
  useEffect(()=>{if(!current)return;const next=current.content||defaultContent;setName(current.name);setCover(current.cover);setFavorite(current.isFavorite);dirty.current=false;setSaveState('已保存');editor?.commands.setContent(next,{emitUpdate:false});const headingChanged=syncFirstHeading(editor,current.name);const synced=editor?.getHTML()??next;setContent(synced);if(headingChanged)dirty.current=true},[current?.id,editor])
  useEffect(()=>{if(!current||!dirty.current)return;setSaveState('正在保存…');const timer=window.setTimeout(()=>{const base=current.revision;void updateJotting(current.id,base,name,content,cover,favorite).then(saved=>{setItems(xs=>xs.map(x=>x.id===saved.id?saved:x));dirty.current=false;setSaveState('已保存')}).catch(cause=>{setSaveState('保存失败');onError(cause instanceof Error?cause.message:'小记保存失败')})},650);return()=>window.clearTimeout(timer)},[content,cover,current?.id,current?.revision,favorite,name,onError])
  const commitDraft=async()=>{if(!draft)return;const value=draft.value.trim();if(!value){setDraft(null);return}try{if(draft.kind==='folder'){const created=await createJottingFolder(value,draft.folderId);setFolders(xs=>[...xs,created]);setExpanded(xs=>new Set(xs).add(created.id));onToast('文件夹已新建')}else{const created=await createJotting(value.endsWith('.md')?value:`${value}.md`,draft.folderId);setItems(xs=>[...xs,created]);setSelectedId(created.id);onToast('小记已新建')}setDraft(null)}catch(cause){onError(cause instanceof Error?cause.message:'创建失败')}}
  const removeFile=async(id:string)=>{await deleteJotting(id);setItems(xs=>xs.filter(x=>x.id!==id));if(selectedId===id)setSelectedId(items.find(x=>x.id!==id)?.id??null);onToast('小记已删除')}
  const removeFolder=async(id:string)=>{await deleteJottingFolder(id);setFolders(xs=>xs.filter(x=>x.id!==id));setItems(xs=>xs.map(x=>x.folderId===id?{...x,folderId:null}:x));onToast('文件夹已删除')}
  const moveItem=async(id:string,folderId:string|null)=>{const item=items.find(value=>value.id===id);if(!item||item.folderId===folderId)return;try{const moved=await moveJotting(id,folderId);setItems(values=>values.map(value=>value.id===id?moved:value));onToast(folderId?'小记已移动到文件夹':'小记已移动到根目录')}catch(cause){onError(cause instanceof Error?cause.message:'移动小记失败')}finally{setDraggingId(null);setDropFolderId(undefined)}}
  const commitRename=async(item:JottingDto)=>{const nextName=renameValue.trim();setRenamingId(null);if(!nextName||nextName===item.name)return;const finalName=nextName.endsWith('.md')?nextName:`${nextName}.md`;if(item.id===selectedId){setName(finalName);setItems(values=>values.map(value=>value.id===item.id?{...value,name:finalName}:value));if(syncFirstHeading(editor,finalName))setContent(editor?.getHTML()??item.content);dirty.current=true;onToast('小记标题与文件名已同步');return}try{const saved=await updateJotting(item.id,item.revision,finalName,item.content,item.cover,item.isFavorite);setItems(values=>values.map(value=>value.id===item.id?saved:value));onToast('小记已重命名')}catch(cause){onError(cause instanceof Error?cause.message:'小记重命名失败')}}
  const beginPointerDrag=(event:React.PointerEvent<HTMLButtonElement>,item:JottingDto)=>{if(event.button!==0||(event.target as Element).closest('[data-tree-action],input'))return;const origin={x:event.clientX,y:event.clientY};let active=false;let targetFolder:string|null|undefined=undefined;const move=(pointer:PointerEvent)=>{if(!active&&Math.hypot(pointer.clientX-origin.x,pointer.clientY-origin.y)<6)return;active=true;setDraggingId(item.id);const folder=(document.elementFromPoint(pointer.clientX,pointer.clientY) as Element|null)?.closest<HTMLElement>('[data-folder-id]');targetFolder=folder?.dataset.folderId??null;setDropFolderId(targetFolder)};const finish=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',finish);if(active&&targetFolder!==undefined)void moveItem(item.id,targetFolder);else{setDraggingId(null);setDropFolderId(undefined)}};window.addEventListener('pointermove',move);window.addEventListener('pointerup',finish,{once:true})}
  const treeFile=(item:JottingDto,depth=0)=><button key={item.id} className={`jotting-tree-row${selectedId===item.id?' active':''}${draggingId===item.id?' is-dragging':''}`} data-kind="file" draggable={renamingId!==item.id} style={{'--depth':depth} as React.CSSProperties} onPointerDown={event=>beginPointerDrag(event,item)} onDragStart={event=>{setDraggingId(item.id);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/coolnote-jotting',item.id)}} onDragEnd={()=>{setDraggingId(null);setDropFolderId(undefined)}} onPointerLeave={()=>setDeleteConfirm(current=>current===item.id?null:current)} onClick={()=>setSelectedId(item.id)}><span className="tree-chevron"/><Icon name="file"/>{renamingId===item.id?<input autoFocus className="jotting-inline-rename" aria-label="重命名小记" value={renameValue} onClick={event=>event.stopPropagation()} onFocus={event=>event.currentTarget.select()} onChange={event=>setRenameValue(event.target.value)} onBlur={()=>void commitRename(item)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();event.currentTarget.blur()}if(event.key==='Escape')setRenamingId(null)}}/>:<span className="tree-name">{item.name}</span>}<span className="tree-inline-action rename" data-tree-action="rename" role="button" aria-label={`重命名${item.name}`} onClick={event=>{event.stopPropagation();setRenamingId(item.id);setRenameValue(item.name)}}><Icon name="pencil"/></span><span className={`tree-inline-action delete${deleteConfirm===item.id?' confirm-delete':''}`} data-tree-action="delete" role="button" aria-label={deleteConfirm===item.id?`确认删除${item.name}`:`删除${item.name}`} onClick={event=>{event.stopPropagation();if(deleteConfirm===item.id){setDeleteConfirm(null);void removeFile(item.id)}else setDeleteConfirm(item.id)}}><Icon name={deleteConfirm===item.id?'check-square':'trash-2'}/></span></button>
  return <>
    <section className="jotting-tree-panel" id="jottingTreePanel" aria-label="小记资源树" data-collapsed={collapsed}><div className="jotting-tree-header"><div className="jotting-tree-heading"><strong>小记</strong><span className="tree-count">{items.length}</span></div><div className="tree-header-actions"><button ref={createButtonRef} className="icon-button" id="jottingCreateButton" aria-label="创建小记或目录" title="创建" onClick={()=>setCreateMenu(x=>!x)}><Icon name="plus"/></button></div></div>
      <nav className={`jotting-tree${dropFolderId===null?' root-drop-target':''}`} id="jottingTree" onDragOver={event=>{if(!draggingId)return;event.preventDefault();if(!(event.target as Element).closest('[data-kind="folder"]'))setDropFolderId(null)}} onDrop={event=>{if((event.target as Element).closest('[data-kind="folder"]'))return;event.preventDefault();const id=event.dataTransfer.getData('text/coolnote-jotting')||draggingId;if(id)void moveItem(id,null)}}>{folders.filter(f=>!f.parentId).map(folder=><div className="jotting-tree-node" key={folder.id}><button className={`jotting-tree-row${dropFolderId===folder.id?' drop-target':''}`} data-kind="folder" data-folder-id={folder.id} data-expanded={expanded.has(folder.id)} style={{'--depth':0} as React.CSSProperties} onDragOver={event=>{if(!draggingId)return;event.preventDefault();event.stopPropagation();setDropFolderId(folder.id)}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setDropFolderId(undefined)}} onDrop={event=>{event.preventDefault();event.stopPropagation();const id=event.dataTransfer.getData('text/coolnote-jotting')||draggingId;if(id)void moveItem(id,folder.id)}} onClick={()=>setExpanded(xs=>{const next=new Set(xs);next.has(folder.id)?next.delete(folder.id):next.add(folder.id);return next})}><span className="tree-chevron"><Icon name="chevron-right"/></span><Icon name={expanded.has(folder.id)?'folder-open':'folder'}/><span className="tree-name">{folder.name}</span><span className="tree-inline-action" data-tree-action="add-file" role="button" aria-label={`在${folder.name}中新建小记`} onClick={event=>{event.stopPropagation();setExpanded(xs=>new Set(xs).add(folder.id));setDraft({kind:'file',folderId:folder.id,value:'未命名小记.md'})}}><Icon name="plus"/></span><span className="tree-inline-action" data-tree-action="delete" role="button" aria-label={`删除${folder.name}`} onClick={event=>{event.stopPropagation();void removeFolder(folder.id)}}><Icon name="trash-2"/></span></button>{expanded.has(folder.id)&&<div className="jotting-tree-children">{items.filter(x=>x.folderId===folder.id).map(x=>treeFile(x,1))}{draft?.folderId===folder.id&&<DraftInput draft={draft} setDraft={setDraft} commit={commitDraft}/>}</div>}</div>)}{items.filter(x=>!x.folderId).map(x=>treeFile(x))}{draft?.folderId===null&&<DraftInput draft={draft} setDraft={setDraft} commit={commitDraft}/>}</nav>
      <FloatingLayer open={createMenu} anchor={createButtonRef} placement="bottom-start" className="product-menu create-dropdown jotting-create-menu" onDismiss={()=>setCreateMenu(false)}><button data-jotting-create="file" onClick={()=>{setDraft({kind:'file',folderId:null,value:'未命名小记.md'});setCreateMenu(false)}}><Icon name="file-plus"/><span><span className="menu-title">新建小记</span><small>创建 Markdown 小记</small></span></button><button data-jotting-create="folder" onClick={()=>{setDraft({kind:'folder',folderId:null,value:'新建文件夹'});setCreateMenu(false)}}><Icon name="folder-plus"/><span><span className="menu-title">新建文件夹</span><small>整理小记内容</small></span></button></FloatingLayer>
    </section>
    <section className="jotting-document-panel" id="jottingWorkspace"><div className="jotting-document-toolbar"><button className="icon-button panel-toggle" id="jottingTreeToggle" aria-label={collapsed?'展开小记导航栏':'折叠小记导航栏'} title={collapsed?'展开小记导航栏':'折叠小记导航栏'} onClick={onToggle}><Icon name={collapsed?'panel-left-open':'panel-left-close'}/></button><div className="jotting-path"><span>小记</span>{currentFolder&&<><Icon name="chevron-right"/><span>{currentFolder.name}</span></>} {current&&<><Icon name="chevron-right"/><strong id="jottingCurrentName">{name}</strong></>}</div><div className="jotting-actions"><span className="save-status jotting-save-status">{saveState}</span>{current&&<><button className={`icon-button${favorite?' active':''}`} aria-label="收藏小记" title="收藏" onClick={()=>{dirty.current=true;setFavorite(x=>!x)}}><Icon name="star"/></button><button ref={moreButtonRef} className="icon-button" aria-label="小记菜单" title="更多" onClick={()=>setMoreMenu(x=>!x)}><Icon name="ellipsis"/></button></>}</div></div>
      <FloatingLayer open={moreMenu&&!!current} anchor={moreButtonRef} placement="bottom-end" className="product-menu document-menu jotting-document-menu" onDismiss={()=>setMoreMenu(false)}>{current&&<button className={`danger${deleteConfirm===current.id?' confirm-delete':''}`} onClick={()=>{if(deleteConfirm===current.id){setDeleteConfirm(null);setMoreMenu(false);void removeFile(current.id)}else setDeleteConfirm(current.id)}}><Icon name={deleteConfirm===current.id?'check-square':'trash-2'}/>{deleteConfirm===current.id?'确认删除小记':'删除小记'}</button>}</FloatingLayer>
      {current?<div className="jotting-document-scroll"><article className="jotting-paper"><div className="jotting-cover"><img id="jottingCoverImage" src={cover||covers[0]} alt="小记封面"/><div className="jotting-cover-actions"><button ref={coverButtonRef} id="chooseBuiltInCover" onClick={()=>setCoverMenu(x=>!x)}><Icon name="image"/>内置图片</button><button id="uploadJottingCover" onClick={()=>uploadRef.current?.click()}><Icon name="image-up"/>上传</button><input ref={uploadRef} type="file" accept="image/*" hidden onChange={event=>{const file=event.target.files?.[0];if(file)void fileData(file).then(data=>{dirty.current=true;setCover(data)});event.target.value=''}}/></div></div><EditorContent editor={editor}/></article><FloatingLayer open={coverMenu} anchor={coverButtonRef} placement="bottom-end" className="jotting-cover-picker open" onDismiss={()=>setCoverMenu(false)}>{covers.map((path,index)=><button className={(cover||covers[0])===path?'active':''} key={path} data-cover={path} aria-label={['天空封面','森林封面','暮色封面'][index]} onClick={()=>{dirty.current=true;setCover(path);setCoverMenu(false)}}><img src={path} alt=""/></button>)}</FloatingLayer></div>:<div className="document-empty"><Icon name="feather" className="empty-document-icon"/><h1>选择或新建一则小记</h1><p>小记内容保存在本机笔记库中。</p></div>}
    </section>
  </>
}

function DraftInput({draft,setDraft,commit}:{draft:Draft;setDraft:(value:Draft|null)=>void;commit:()=>void}){const done=useRef(false);const finish=()=>{if(done.current)return;done.current=true;void commit()};return <div className="jotting-tree-draft"><input autoFocus aria-label={draft.kind==='folder'?'文件夹名称':'小记名称'} value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();finish()}if(e.key==='Escape'){done.current=true;setDraft(null)}}} onBlur={finish}/></div>}
