import Link from '@tiptap/extension-link'
import Image from '@tiptap/extension-image'
import type { Editor } from '@tiptap/core'
import Underline from '@tiptap/extension-underline'
import { EditorContent, useEditor } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import { useEffect, useRef, useState } from 'react'

import { Icon } from '../../shared/components/Icon'
import { FloatingLayer } from '../../shared/components/Overlay'
import { ContentSkeleton, SidebarSkeleton } from '../../shared/components/Skeleton'
import { BUILT_IN_COVERS } from '../../shared/covers'
import { downloadText, exportElementAsLongImage, exportElementAsPdf, htmlToMarkdown, safeFileName } from '../export/export'
import { createJotting, createJottingFolder, deleteJotting, deleteJottingFolder, getJottingSnapshot, moveJotting, updateJotting } from '../../shared/tauri/commands'
import type { JottingDto, JottingFolderDto } from '../../shared/tauri/contracts'

type Props={collapsed:boolean;openJottingId?:string|null;onToggle:()=>void;onToast:(message:string)=>void;onError:(message:string)=>void}
type Draft={kind:'file'|'folder';folderId:string|null;value:string}
type Point={left:number;top:number}
const defaultContent='<h1>无标题</h1><p><em>从此刻开始，写下一则小记。</em></p><p><br></p>'
const fileData=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})
const titleFromName=(name:string)=>name.replace(/\.md$/i,'').trim()||'无标题'
const nameFromTitle=(title:string)=>(title.replace(/[\\/:*?"<>|]/g,'-').replace(/\.md$/i,'').trim()||'无标题')
const formatJottingDate=(value:string)=>{const date=new Date(value);return`${date.getFullYear()}.${date.getMonth()+1}.${date.getDate()} ${date.getHours()}:${String(date.getMinutes()).padStart(2,'0')}`}
const syncFirstHeading=(editor:Editor|null,name:string)=>{if(!editor)return false;const json=editor.getJSON() as any;const first=json.content?.[0];const title=titleFromName(name);if(first?.type==='heading'&&first.attrs?.level===1){const current=first.content?.map((node:any)=>node.text??'').join('')??'';if(current===title)return false;first.content=[{type:'text',text:title}]}else json.content=[{type:'heading',attrs:{level:1},content:[{type:'text',text:title}]},...(json.content??[])];editor.commands.setContent(json,{emitUpdate:false});return true}

export function JottingsWorkspace({collapsed,openJottingId,onToggle,onToast,onError}:Props){
  const [folders,setFolders]=useState<JottingFolderDto[]>([]);const [items,setItems]=useState<JottingDto[]>([]);const [loading,setLoading]=useState(true)
  const [selectedId,setSelectedId]=useState<string|null>(null);const [expanded,setExpanded]=useState<Set<string>>(new Set())
  const [draft,setDraft]=useState<Draft|null>(null);const [renamingId,setRenamingId]=useState<string|null>(null);const [renameValue,setRenameValue]=useState('');const [createMenu,setCreateMenu]=useState(false);const [coverMenu,setCoverMenu]=useState(false);const [moreMenu,setMoreMenu]=useState(false);const [deleteConfirm,setDeleteConfirm]=useState<string|null>(null);const [draggingId,setDraggingId]=useState<string|null>(null);const [dropFolderId,setDropFolderId]=useState<string|null|undefined>(undefined);const [selection,setSelection]=useState<Point|null>(null)
  const [content,setContent]=useState(defaultContent);const [name,setName]=useState('未命名小记');const [cover,setCover]=useState<string|null>(null);const [favorite,setFavorite]=useState(false);const [saveState,setSaveState]=useState('已保存')
  const dirty=useRef(false);const initialized=useRef(false);const savePromise=useRef<Promise<boolean>|null>(null);const onErrorRef=useRef(onError);const uploadRef=useRef<HTMLInputElement>(null);const bodyUploadRef=useRef<HTMLInputElement>(null);const paperRef=useRef<HTMLElement>(null);const createButtonRef=useRef<HTMLButtonElement>(null);const coverButtonRef=useRef<HTMLButtonElement>(null);const moreButtonRef=useRef<HTMLButtonElement>(null);const current=items.find(item=>item.id===selectedId)??null
  const currentFolder=current?.folderId?folders.find(folder=>folder.id===current.folderId)??null:null
  const insertImages=async(files:File[],position?:number)=>{const images=await Promise.all(files.filter(file=>file.type.startsWith('image/')).map(async file=>({type:'image',attrs:{src:await fileData(file),alt:file.name,title:file.name}})));if(!editor||!images.length)return;const chain=editor.chain().focus();if(typeof position==='number')chain.insertContentAt(position,images).run();else chain.insertContent(images).run()}
  const updateSelection=(active:Editor)=>{const {from,to}=active.state.selection;if(from===to||(active.state.selection as any).node){setSelection(null);return}try{const start=active.view.coordsAtPos(from),end=active.view.coordsAtPos(to);setSelection({left:start.left,top:Math.min(start.top,end.top)-8})}catch{setSelection(null)}}
  const editor=useEditor({immediatelyRender:false,extensions:[StarterKit.configure({heading:{levels:[1,2,3,4,5]}}),Underline,Link.configure({openOnClick:false,autolink:true}),Image.configure({allowBase64:true,inline:false})],content,editorProps:{attributes:{class:'jotting-markdown','aria-label':'小记 Markdown 正文'},handlePaste:(view,event)=>{const files=Array.from(event.clipboardData?.files??[]).filter(file=>file.type.startsWith('image/'));if(!files.length)return false;event.preventDefault();void insertImages(files,view.state.selection.from);return true},handleDrop:(view,event)=>{const files=Array.from(event.dataTransfer?.files??[]).filter(file=>file.type.startsWith('image/'));if(!files.length)return false;event.preventDefault();const point=view.posAtCoords({left:event.clientX,top:event.clientY});void insertImages(files,point?.pos??view.state.selection.from);return true}},onSelectionUpdate:({editor:active})=>updateSelection(active),onBlur:()=>window.setTimeout(()=>setSelection(null),120),onUpdate:({editor:active})=>{dirty.current=true;setContent(active.getHTML());const first=(active.getJSON() as any).content?.[0];if(first?.type==='heading'&&first.attrs?.level===1){const nextName=nameFromTitle(first.content?.map((node:any)=>node.text??'').join('')??'');setName(nextName);if(selectedId)setItems(values=>values.map(value=>value.id===selectedId?{...value,name:nextName}:value))}}})
  const saveCurrent=async()=>{if(savePromise.current)return savePromise.current;if(!current||!dirty.current)return true;setSaveState('正在保存…');const task=(async()=>{try{const saved=await updateJotting(current.id,current.revision,nameFromTitle(name),content,cover,favorite);setItems(xs=>xs.map(x=>x.id===saved.id?{...saved,name:titleFromName(saved.name)}:x));dirty.current=false;setSaveState('已保存');return true}catch(cause){setSaveState('保存失败');onErrorRef.current(cause instanceof Error?cause.message:'小记保存失败');return false}finally{savePromise.current=null}})();savePromise.current=task;return task}
  const selectItem=async(id:string)=>{if(id===selectedId)return;if(await saveCurrent())setSelectedId(id)}
  useEffect(()=>{onErrorRef.current=onError},[onError])
  useEffect(()=>{if(initialized.current)return;initialized.current=true;void getJottingSnapshot().then(snapshot=>{const nextFolders=[...new Map(snapshot.folders.map(item=>[item.id,item])).values()];const nextItems=[...new Map(snapshot.jottings.map(item=>[item.id,{...item,name:titleFromName(item.name),isFavorite:item.isFavorite??false}])).values()];const preferred=openJottingId&&nextItems.some(item=>item.id===openJottingId)?openJottingId:nextItems[0]?.id??null;setFolders(nextFolders);setItems(nextItems);setSelectedId(preferred);const folderId=nextItems.find(item=>item.id===preferred)?.folderId;setExpanded(folderId?new Set([folderId]):new Set())}).catch(cause=>onErrorRef.current(cause instanceof Error?cause.message:'无法打开小记')).finally(()=>setLoading(false))},[])
  useEffect(()=>{if(openJottingId&&items.some(item=>item.id===openJottingId))void selectItem(openJottingId)},[openJottingId])
  useEffect(()=>{if(!current)return;const next=current.content||defaultContent;const normalizedName=titleFromName(current.name);setName(normalizedName);setCover(current.cover);setFavorite(current.isFavorite);dirty.current=false;setSaveState('已保存');editor?.commands.setContent(next,{emitUpdate:false});const headingChanged=syncFirstHeading(editor,normalizedName);const synced=editor?.getHTML()??next;setContent(synced);if(headingChanged||normalizedName!==current.name)dirty.current=true},[current?.id,editor])
  useEffect(()=>{if(!current||!dirty.current)return;setSaveState('正在保存…');const timer=window.setTimeout(()=>void saveCurrent(),650);return()=>window.clearTimeout(timer)},[content,cover,current?.id,current?.revision,favorite,name])
  const commitDraft=async()=>{if(!draft)return;const value=draft.value.trim();if(!value){setDraft(null);return}try{if(draft.kind==='folder'){const created=await createJottingFolder(value,draft.folderId);setFolders(xs=>[...xs,created]);setExpanded(xs=>new Set(xs).add(created.id));onToast('文件夹已新建')}else{if(!(await saveCurrent()))return;const created=await createJotting(nameFromTitle(value),draft.folderId);setItems(xs=>[...xs,{...created,name:titleFromName(created.name)}]);setSelectedId(created.id);onToast('小记已新建')}setDraft(null)}catch(cause){onErrorRef.current(cause instanceof Error?cause.message:'创建失败')}}
  const removeFile=async(id:string)=>{await deleteJotting(id);setItems(xs=>xs.filter(x=>x.id!==id));if(selectedId===id)setSelectedId(items.find(x=>x.id!==id)?.id??null);onToast('小记已删除')}
  const removeFolder=async(id:string)=>{await deleteJottingFolder(id);setFolders(xs=>xs.filter(x=>x.id!==id));setItems(xs=>xs.map(x=>x.folderId===id?{...x,folderId:null}:x));onToast('文件夹已删除')}
  const moveItem=async(id:string,folderId:string|null)=>{const item=items.find(value=>value.id===id);if(!item||item.folderId===folderId)return;try{const moved=await moveJotting(id,folderId);setItems(values=>values.map(value=>value.id===id?moved:value));onToast(folderId?'小记已移动到文件夹':'小记已移动到根目录')}catch(cause){onError(cause instanceof Error?cause.message:'移动小记失败')}finally{setDraggingId(null);setDropFolderId(undefined)}}
  const commitRename=async(item:JottingDto)=>{const finalName=nameFromTitle(renameValue);setRenamingId(null);if(!finalName||finalName===titleFromName(item.name))return;if(item.id===selectedId){setName(finalName);setItems(values=>values.map(value=>value.id===item.id?{...value,name:finalName}:value));if(syncFirstHeading(editor,finalName))setContent(editor?.getHTML()??item.content);dirty.current=true;onToast('小记标题与名称已同步');return}try{const saved=await updateJotting(item.id,item.revision,finalName,item.content,item.cover,item.isFavorite);setItems(values=>values.map(value=>value.id===item.id?{...saved,name:titleFromName(saved.name)}:value));onToast('小记已重命名')}catch(cause){onErrorRef.current(cause instanceof Error?cause.message:'小记重命名失败')}}
  const beginPointerDrag=(event:React.PointerEvent<HTMLButtonElement>,item:JottingDto)=>{if(event.button!==0||(event.target as Element).closest('[data-tree-action],input'))return;const origin={x:event.clientX,y:event.clientY};let active=false;let targetFolder:string|null|undefined=undefined;const move=(pointer:PointerEvent)=>{if(!active&&Math.hypot(pointer.clientX-origin.x,pointer.clientY-origin.y)<6)return;active=true;setDraggingId(item.id);const folder=(document.elementFromPoint(pointer.clientX,pointer.clientY) as Element|null)?.closest<HTMLElement>('[data-folder-id]');targetFolder=folder?.dataset.folderId??null;setDropFolderId(targetFolder)};const finish=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',finish);if(active&&targetFolder!==undefined)void moveItem(item.id,targetFolder);else{setDraggingId(null);setDropFolderId(undefined)}};window.addEventListener('pointermove',move);window.addEventListener('pointerup',finish,{once:true})}
  const exportJotting=async(format:'image'|'markdown'|'pdf')=>{if(!current)return;const title=titleFromName(name);try{let saved=false;if(format==='markdown')saved=await downloadText(`${safeFileName(title)}.md`,htmlToMarkdown(editor?.getHTML()??content),'text/markdown;charset=utf-8');if(format==='pdf'&&paperRef.current)saved=await exportElementAsPdf(paperRef.current,`${safeFileName(title)}.pdf`);if(format==='image'&&paperRef.current)saved=await exportElementAsLongImage(paperRef.current,`${safeFileName(title)}.png`);setMoreMenu(false);if(saved)onToast(format==='image'?'长图已导出':format==='markdown'?'Markdown 已导出':'PDF 已导出')}catch(cause){onError(cause instanceof Error?cause.message:'导出失败')}}
  const treeFile=(item:JottingDto,depth=0)=><button key={item.id} className={`jotting-tree-row${selectedId===item.id?' active':''}${draggingId===item.id?' is-dragging':''}`} data-kind="file" draggable={renamingId!==item.id} style={{'--depth':depth} as React.CSSProperties} onPointerDown={event=>beginPointerDrag(event,item)} onDragStart={event=>{setDraggingId(item.id);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/coolnote-jotting',item.id)}} onDragEnd={()=>{setDraggingId(null);setDropFolderId(undefined)}} onPointerLeave={()=>setDeleteConfirm(current=>current===item.id?null:current)} onClick={()=>void selectItem(item.id)}><span className="tree-chevron"/><Icon name="file"/>{renamingId===item.id?<input autoFocus className="jotting-inline-rename" aria-label="重命名小记" value={renameValue} onClick={event=>event.stopPropagation()} onFocus={event=>event.currentTarget.select()} onChange={event=>setRenameValue(event.target.value)} onBlur={()=>void commitRename(item)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();event.currentTarget.blur()}if(event.key==='Escape')setRenamingId(null)}}/>:<span className="tree-name">{titleFromName(item.name)}</span>}<span className="tree-inline-action rename" data-tree-action="rename" role="button" aria-label={`重命名${titleFromName(item.name)}`} onClick={event=>{event.stopPropagation();setRenamingId(item.id);setRenameValue(titleFromName(item.name))}}><Icon name="pencil"/></span><span className={`tree-inline-action delete${deleteConfirm===item.id?' confirm-delete':''}`} data-tree-action="delete" role="button" aria-label={deleteConfirm===item.id?`确认删除${titleFromName(item.name)}`:`删除${titleFromName(item.name)}`} onClick={event=>{event.stopPropagation();if(deleteConfirm===item.id){setDeleteConfirm(null);void removeFile(item.id)}else setDeleteConfirm(item.id)}}><Icon name={deleteConfirm===item.id?'check-square':'trash-2'}/></span></button>
  if(loading)return <><section className="jotting-tree-panel" aria-label="正在加载小记资源树" data-collapsed={collapsed}><div className="jotting-tree-header"><div className="jotting-tree-heading"><strong>小记</strong><span className="tree-count"/></div></div><SidebarSkeleton rows={7}/></section><section className="jotting-document-panel"><div className="jotting-document-toolbar"><button className="icon-button panel-toggle" aria-label="折叠小记导航栏" onClick={onToggle}><Icon name="panel-left-close"/></button></div><ContentSkeleton cards={3}/></section></>
  return <>
    <section className="jotting-tree-panel" id="jottingTreePanel" aria-label="小记资源树" data-collapsed={collapsed}>
      <div className="jotting-tree-header"><div className="jotting-tree-heading"><strong>小记</strong><span className="tree-count">{items.length}</span></div><div className="tree-header-actions"><button ref={createButtonRef} className="icon-button" id="jottingCreateButton" aria-label="创建小记或目录" title="创建" onClick={()=>setCreateMenu(x=>!x)}><Icon name="plus"/></button></div></div>
      {loading&&<SidebarSkeleton rows={7}/>}
      <nav className={`jotting-tree${dropFolderId===null?' root-drop-target':''}`} id="jottingTree" onDragOver={event=>{if(!draggingId)return;event.preventDefault();if(!(event.target as Element).closest('[data-kind="folder"]'))setDropFolderId(null)}} onDrop={event=>{if((event.target as Element).closest('[data-kind="folder"]'))return;event.preventDefault();const id=event.dataTransfer.getData('text/coolnote-jotting')||draggingId;if(id)void moveItem(id,null)}}>{folders.filter(f=>!f.parentId).map(folder=><div className="jotting-tree-node" key={folder.id}><button className={`jotting-tree-row${dropFolderId===folder.id?' drop-target':''}`} data-kind="folder" data-folder-id={folder.id} data-expanded={expanded.has(folder.id)} style={{'--depth':0} as React.CSSProperties} onDragOver={event=>{if(!draggingId)return;event.preventDefault();event.stopPropagation();setDropFolderId(folder.id)}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setDropFolderId(undefined)}} onDrop={event=>{event.preventDefault();event.stopPropagation();const id=event.dataTransfer.getData('text/coolnote-jotting')||draggingId;if(id)void moveItem(id,folder.id)}} onClick={()=>setExpanded(xs=>{const next=new Set(xs);next.has(folder.id)?next.delete(folder.id):next.add(folder.id);return next})}><span className="tree-chevron"><Icon name="chevron-right"/></span><Icon name={expanded.has(folder.id)?'folder-open':'folder'}/><span className="tree-name">{folder.name}</span><span className="tree-inline-action" data-tree-action="add-file" role="button" aria-label={`在${folder.name}中新建小记`} onClick={event=>{event.stopPropagation();setExpanded(xs=>new Set(xs).add(folder.id));setDraft({kind:'file',folderId:folder.id,value:'未命名小记'})}}><Icon name="plus"/></span><span className="tree-inline-action" data-tree-action="delete" role="button" aria-label={`删除${folder.name}`} onClick={event=>{event.stopPropagation();void removeFolder(folder.id)}}><Icon name="trash-2"/></span></button>{expanded.has(folder.id)&&<div className="jotting-tree-children">{items.filter(x=>x.folderId===folder.id).map(x=>treeFile(x,1))}{draft?.folderId===folder.id&&<DraftInput draft={draft} setDraft={setDraft} commit={commitDraft}/>}</div>}</div>)}{items.filter(x=>!x.folderId).map(x=>treeFile(x))}{draft?.folderId===null&&<DraftInput draft={draft} setDraft={setDraft} commit={commitDraft}/>}</nav>
      <FloatingLayer open={createMenu} anchor={createButtonRef} placement="bottom-start" className="product-menu create-dropdown jotting-create-menu" onDismiss={()=>setCreateMenu(false)}><button data-jotting-create="file" onClick={()=>{setDraft({kind:'file',folderId:null,value:'未命名小记'});setCreateMenu(false)}}><Icon name="file-plus"/><span><span className="menu-title">新建小记</span><small>创建小记文档</small></span></button><button data-jotting-create="folder" onClick={()=>{setDraft({kind:'folder',folderId:null,value:'新建文件夹'});setCreateMenu(false)}}><Icon name="folder-plus"/><span><span className="menu-title">新建文件夹</span><small>整理小记内容</small></span></button></FloatingLayer>
    </section>
    <section className="jotting-document-panel" id="jottingWorkspace"><div className="jotting-document-toolbar"><button className="icon-button panel-toggle" id="jottingTreeToggle" aria-label={collapsed?'展开小记导航栏':'折叠小记导航栏'} title={collapsed?'展开小记导航栏':'折叠小记导航栏'} onClick={onToggle}><Icon name={collapsed?'panel-left-open':'panel-left-close'}/></button><div className="jotting-path"><span>小记</span>{currentFolder&&<><Icon name="chevron-right"/><span>{currentFolder.name}</span></>} {current&&<><Icon name="chevron-right"/><strong id="jottingCurrentName">{name}</strong></>}</div><div className="jotting-actions"><span className="save-status jotting-save-status">{saveState}</span>{current&&<><button className={`icon-button${favorite?' active':''}`} aria-label="收藏小记" title="收藏" onClick={()=>{dirty.current=true;setFavorite(x=>!x)}}><Icon name="star"/></button><button ref={moreButtonRef} className="icon-button" aria-label="小记菜单" title="更多" onClick={()=>setMoreMenu(x=>!x)}><Icon name="ellipsis"/></button></>}</div></div>
      <FloatingLayer open={moreMenu&&!!current} anchor={moreButtonRef} placement="bottom-end" className="product-menu document-menu jotting-document-menu" onDismiss={()=>setMoreMenu(false)}>{current&&<><button onClick={()=>{bodyUploadRef.current?.click();setMoreMenu(false)}}><Icon name="image-up"/>插入图片</button><button onClick={()=>void exportJotting('image')}><Icon name="image"/>导出长图</button><button onClick={()=>void exportJotting('markdown')}><Icon name="download"/>导出 Markdown</button><button onClick={()=>void exportJotting('pdf')}><Icon name="download"/>导出 PDF</button><div className="separator"/><button className={`danger${deleteConfirm===current.id?' confirm-delete':''}`} onClick={()=>{if(deleteConfirm===current.id){setDeleteConfirm(null);setMoreMenu(false);void removeFile(current.id)}else setDeleteConfirm(current.id)}}><Icon name={deleteConfirm===current.id?'check-square':'trash-2'}/>{deleteConfirm===current.id?'确认删除小记':'删除小记'}</button></>}</FloatingLayer>
      {current?<div className="jotting-document-scroll"><article ref={paperRef} className="jotting-paper"><div className="jotting-cover"><img id="jottingCoverImage" src={cover||BUILT_IN_COVERS[0].src} alt="小记封面"/><div className="jotting-cover-actions"><button ref={coverButtonRef} id="chooseBuiltInCover" onClick={()=>setCoverMenu(x=>!x)}><Icon name="image"/>内置图片</button><button id="uploadJottingCover" onClick={()=>uploadRef.current?.click()}><Icon name="image-up"/>上传</button><input ref={uploadRef} type="file" accept="image/*" hidden onChange={event=>{const file=event.target.files?.[0];if(file)void fileData(file).then(data=>{dirty.current=true;setCover(data)});event.target.value=''}}/></div></div><EditorContent editor={editor}/><time className="jotting-date-signature" dateTime={current.updatedAt}>{formatJottingDate(current.updatedAt)}</time></article><FloatingLayer open={!!selection} point={selection??undefined} placement="top-start" gap={8} className="selection-toolbar jotting-selection-toolbar product-layer" onDismiss={()=>setSelection(null)}>{selection&&<div className="selection-toolbar-inner" onMouseDown={event=>event.preventDefault()}>{([1,2,3] as const).map(level=><button key={level} className={editor?.isActive('heading',{level})?'active':''} onClick={()=>editor?.chain().focus().toggleHeading({level}).run()}>H{level}</button>)}<span className="divider"/><button className={editor?.isActive('bold')?'active':''} onClick={()=>editor?.chain().focus().toggleBold().run()}><strong>B</strong></button><button onClick={()=>editor?.chain().focus().toggleItalic().run()}><i>I</i></button><button onClick={()=>editor?.chain().focus().toggleUnderline().run()}><u>U</u></button><button onClick={()=>editor?.chain().focus().toggleStrike().run()}><s>S</s></button><button onClick={()=>editor?.chain().focus().toggleCode().run()}><Icon name="code"/></button></div>}</FloatingLayer><FloatingLayer open={coverMenu} anchor={coverButtonRef} placement="bottom-end" className="jotting-cover-picker open" onDismiss={()=>setCoverMenu(false)}>{BUILT_IN_COVERS.map(item=><button className={(cover||BUILT_IN_COVERS[0].src)===item.src?'active':''} key={item.src} data-cover={item.src} aria-label={item.label} onClick={()=>{dirty.current=true;setCover(item.src);setCoverMenu(false)}}><img src={item.src} alt=""/></button>)}</FloatingLayer><input ref={bodyUploadRef} hidden multiple type="file" accept="image/*" onChange={event=>{const files=Array.from(event.target.files??[]);if(files.length)void insertImages(files);event.target.value=''}}/></div>:<div className="document-empty"><Icon name="feather" className="empty-document-icon"/><h1>选择或新建一则小记</h1><p>小记内容保存在本机笔记库中。</p></div>}
    </section>
  </>
}

function DraftInput({draft,setDraft,commit}:{draft:Draft;setDraft:(value:Draft|null)=>void;commit:()=>void}){const done=useRef(false);const finish=()=>{if(done.current)return;done.current=true;void commit()};return <div className="jotting-tree-draft"><input autoFocus aria-label={draft.kind==='folder'?'文件夹名称':'小记名称'} value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();finish()}if(e.key==='Escape'){done.current=true;setDraft(null)}}} onBlur={finish}/></div>}
