import { open, save } from '@tauri-apps/plugin-dialog'
import { writeFile } from '@tauri-apps/plugin-fs'
import { useEffect, useMemo, useRef, useState } from 'react'

import { Icon } from '../../shared/components/Icon'
import { FloatingLayer, ProductProgressToast, type DialogState } from '../../shared/components/Overlay'
import { ContentSkeleton, SidebarSkeleton } from '../../shared/components/Skeleton'
import { BUILT_IN_COVERS } from '../../shared/covers'
import {
  createGallery, deleteGallery, deleteGalleryItems, getGalleryAssetData, importGalleryData, importGalleryPath,
  listGalleries, listGalleryItems, reorderGallery, reorderGalleryItem, transferGalleryItems,
  undoGalleryDelete, updateGallery,
} from '../../shared/tauri/commands'
import type { GalleryAssetDataDto, GalleryItemDto, GallerySummaryDto } from '../../shared/tauri/contracts'

type Props={collapsed:boolean;openGalleryId?:string|null;onToggle:()=>void;onToast:(message:string,undo?:()=>void|Promise<void>)=>void;onError:(message:string)=>void;onCountChange:(count:number)=>void;onConfirm:(state:DialogState)=>void}
type ImportState={id:number;current:number;total:number;added:number;skipped:number;failed:Array<{name:string;message:string}>;cancelled:boolean}
type TransferState={ids:string[];move:boolean}|null
const PAGE_SIZE=60
const native=typeof window!=='undefined'&&'__TAURI_INTERNALS__' in window
const dataUrlBytes=(dataUrl:string)=>{const base64=dataUrl.split(',')[1]??'';const binary=atob(base64);return Uint8Array.from(binary,char=>char.charCodeAt(0))}
const fileDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})
const writeImageToClipboard=async(dataUrl:string)=>{let blob=await(await fetch(dataUrl)).blob();if(blob.type!=='image/png'){const image=new Image();image.src=dataUrl;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d')?.drawImage(image,0,0);blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('无法转换剪贴板图片')),'image/png'))}await navigator.clipboard.write([new ClipboardItem({'image/png':blob})])}

export function GalleryWorkspace({collapsed,openGalleryId,onToggle,onToast,onError,onCountChange,onConfirm}:Props){
  const [galleries,setGalleries]=useState<GallerySummaryDto[]>([]);const [selectedId,setSelectedId]=useState<string|null>(null)
  const [items,setItems]=useState<GalleryItemDto[]>([]);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [loadingMore,setLoadingMore]=useState(false)
  const [draftName,setDraftName]=useState<string|null>(null);const [renamingId,setRenamingId]=useState<string|null>(null);const [renameValue,setRenameValue]=useState('')
  const [name,setName]=useState('');const [introduction,setIntroduction]=useState('');const [cover,setCover]=useState<string|null>(null);const [coverMenu,setCoverMenu]=useState(false);const [saveState,setSaveState]=useState('已保存');const dirty=useRef(false);const coverButtonRef=useRef<HTMLButtonElement>(null);const coverUploadRef=useRef<HTMLInputElement>(null)
  const [selected,setSelected]=useState<Set<string>>(new Set());const [selecting,setSelecting]=useState(false);const [draggingItemId,setDraggingItemId]=useState<string|null>(null);const [lightbox,setLightbox]=useState<{item:GalleryItemDto;asset:GalleryAssetDataDto|null}|null>(null)
  const [importState,setImportState]=useState<ImportState|null>(null);const cancelImport=useRef(false);const [transfer,setTransfer]=useState<TransferState>(null);const [dropActive,setDropActive]=useState(false)
  const current=galleries.find(value=>value.id===selectedId)??null
  const currentIndex=lightbox?items.findIndex(item=>item.id===lightbox.item.id):-1

  const refreshGalleries=async(preferred?:string|null)=>{const values=await listGalleries();setGalleries(values);onCountChange(values.length);setSelectedId(currentId=>{if(preferred&&values.some(x=>x.id===preferred))return preferred;if(currentId&&values.some(x=>x.id===currentId))return currentId;return values[0]?.id??null})}
  const loadItems=async(galleryId:string,append=false)=>{append?setLoadingMore(true):setLoading(true);try{const page=await listGalleryItems(galleryId,append?items.length:0,PAGE_SIZE);setItems(values=>append?[...values,...page.items]:page.items);setTotal(page.total)}finally{append?setLoadingMore(false):setLoading(false)}}
  useEffect(()=>{void refreshGalleries(openGalleryId).catch(cause=>onError(cause instanceof Error?cause.message:'无法打开画廊'))},[])
  useEffect(()=>{if(openGalleryId&&galleries.some(x=>x.id===openGalleryId))setSelectedId(openGalleryId)},[openGalleryId,galleries])
  useEffect(()=>{if(!current){setItems([]);setTotal(0);setName('');setIntroduction('');setCover(null);return}setName(current.name);setIntroduction(current.introduction);setCover(current.cover);dirty.current=false;setSaveState('已保存');setSelected(new Set());setSelecting(false);void loadItems(current.id).catch(cause=>onError(cause instanceof Error?cause.message:'无法加载画廊图片'))},[current?.id])
  useEffect(()=>{if(!current||!dirty.current)return;setSaveState('保存中…');const timer=window.setTimeout(()=>{const base=current.revision;void updateGallery(current.id,base,name,introduction,cover).then(saved=>{setGalleries(values=>values.map(value=>value.id===saved.id?saved:value));dirty.current=false;setSaveState('已保存')}).catch(cause=>{setSaveState('保存失败');onError(cause instanceof Error?cause.message:'画廊保存失败')})},300);return()=>window.clearTimeout(timer)},[name,introduction,cover,current?.id,current?.revision,onError])
  useEffect(()=>{if(!lightbox)return;const key=(event:KeyboardEvent)=>{if(event.key==='Escape')setLightbox(null);if(event.key==='ArrowLeft')void openAt(currentIndex-1);if(event.key==='ArrowRight')void openAt(currentIndex+1)};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[lightbox,currentIndex,items])

  const create=async()=>{const value=draftName?.trim();setDraftName(null);if(!value)return;try{const created=await createGallery(value);await refreshGalleries(created.id);onToast('画廊已新建')}catch(cause){onError(cause instanceof Error?cause.message:'创建画廊失败')}}
  const rename=async(gallery:GallerySummaryDto)=>{const value=renameValue.trim();setRenamingId(null);if(!value||value===gallery.name)return;try{const saved=await updateGallery(gallery.id,gallery.revision,value,gallery.introduction,gallery.cover);setGalleries(values=>values.map(item=>item.id===saved.id?saved:item));if(saved.id===selectedId){setName(saved.name);setIntroduction(saved.introduction);setCover(saved.cover)}onToast('画廊已重命名')}catch(cause){onError(cause instanceof Error?cause.message:'重命名失败')}}
  const removeGallery=(gallery:GallerySummaryDto)=>onConfirm({title:'删除画廊',description:`“${gallery.name}”及其中 ${gallery.itemCount} 张图片将被移除，可在 8 秒内撤销。`,confirmLabel:'删除画廊',danger:true,onConfirm:async()=>{const token=await deleteGallery(gallery.id);await refreshGalleries();onToast('画廊已删除',async()=>{if(await undoGalleryDelete(token)){await refreshGalleries(gallery.id);onToast('删除已撤销')}})}})
  const deleteItems=async(ids:string[])=>{if(!ids.length)return;const token=await deleteGalleryItems(ids);setItems(values=>values.filter(item=>!ids.includes(item.id)));setTotal(value=>Math.max(0,value-ids.length));setSelected(new Set());setSelecting(false);await refreshGalleries(selectedId);onToast(ids.length===1?'图片已删除':`已删除 ${ids.length} 张图片`,async()=>{if(await undoGalleryDelete(token)){if(selectedId)await loadItems(selectedId);await refreshGalleries(selectedId);onToast('删除已撤销')}})}
  const confirmBatchDelete=()=>onConfirm({title:'删除所选图片',description:`将从当前画廊移除 ${selected.size} 张图片，可在 8 秒内撤销。`,confirmLabel:'删除图片',danger:true,onConfirm:()=>deleteItems([...selected])})
  const chooseFiles=async()=>{if(!native){onError('浏览器预览模式不支持真实图片导入，请使用 Tauri 开发模式。');return}const paths=await open({multiple:true,directory:false,filters:[{name:'图片',extensions:['jpg','jpeg','png','webp','gif']}]});if(paths?.length)await importPaths(paths)}
  const handleFileDrop=(event:React.DragEvent)=>{event.preventDefault();setDropActive(false);const files=[...event.dataTransfer.files];const paths=files.map(file=>(file as File&{path?:string}).path).filter((path):path is string=>!!path);if(paths.length===files.length){void importPaths(paths);return}void importDroppedFiles(files)}
  const importDroppedFiles=async(files:File[])=>{if(!selectedId||!files.length)return;cancelImport.current=false;let state:ImportState={id:Date.now(),current:0,total:files.length,added:0,skipped:0,failed:[],cancelled:false};setImportState(state);for(const file of files){if(cancelImport.current){state={...state,cancelled:true};break}try{const result=await importGalleryData(selectedId,file.name,await fileDataUrl(file));state={...state,current:state.current+1,added:state.added+(result.status==='added'?1:0),skipped:state.skipped+(result.status==='skipped'?1:0)}}catch(cause){state={...state,current:state.current+1,failed:[...state.failed,{name:file.name,message:cause instanceof Error?cause.message:'导入失败'}]}}setImportState(state)}await loadItems(selectedId);await refreshGalleries(selectedId);setImportState(state);onToast(`已添加 ${state.added} 张，跳过 ${state.skipped} 张，失败 ${state.failed.length} 张${state.cancelled?'，导入已取消':''}`)}
  const importPaths=async(paths:string[])=>{if(!selectedId||!paths.length)return;cancelImport.current=false;let state:ImportState={id:Date.now(),current:0,total:paths.length,added:0,skipped:0,failed:[],cancelled:false};setImportState(state);for(const path of paths){if(cancelImport.current){state={...state,cancelled:true};break}try{const result=await importGalleryPath(selectedId,path);state={...state,current:state.current+1,added:state.added+(result.status==='added'?1:0),skipped:state.skipped+(result.status==='skipped'?1:0)}}catch(cause){state={...state,current:state.current+1,failed:[...state.failed,{name:path.split(/[\\/]/).pop()??path,message:cause instanceof Error?cause.message:'导入失败'}]}}setImportState(state)}await loadItems(selectedId);await refreshGalleries(selectedId);setImportState(state);const message=`已添加 ${state.added} 张，跳过 ${state.skipped} 张，失败 ${state.failed.length} 张${state.cancelled?'，导入已取消':''}`;onToast(message)}
  const dragGallery=async(id:string,beforeId:string|null)=>{await reorderGallery(id,beforeId);await refreshGalleries(selectedId)}
  const dragItem=async(itemId:string,beforeId:string|null)=>{if(!selectedId)return;await reorderGalleryItem(selectedId,itemId,beforeId);await loadItems(selectedId)}
  const runTransfer=async(targetGalleryId:string)=>{if(!transfer)return;const result=await transferGalleryItems(transfer.ids,targetGalleryId,transfer.move);setTransfer(null);setSelected(new Set());setSelecting(false);if(selectedId)await loadItems(selectedId);await refreshGalleries(selectedId);onToast(`${transfer.move?'移动':'复制'}完成：${result.changed} 张${result.skipped?`，跳过 ${result.skipped} 张`:''}`)}
  const openAt=async(index:number)=>{if(index<0||index>=items.length)return;const item=items[index];setLightbox({item,asset:null});try{const asset=await getGalleryAssetData(item.id);setLightbox(currentValue=>currentValue?.item.id===item.id?{item,asset}:currentValue)}catch(cause){onError(cause instanceof Error?cause.message:'无法读取原图')}}
  const copyItem=async(item:GalleryItemDto)=>{try{await writeImageToClipboard((await getGalleryAssetData(item.id)).dataUrl);onToast('图片已复制到剪贴板')}catch(cause){onError(cause instanceof Error?cause.message:'复制图片失败')}}
  const copyLightbox=async()=>{if(!lightbox?.asset)return;try{await writeImageToClipboard(lightbox.asset.dataUrl);onToast('图片已复制到剪贴板')}catch(cause){onError(cause instanceof Error?cause.message:'复制图片失败')}}
  const saveLightbox=async()=>{if(!lightbox?.asset)return;const path=await save({defaultPath:lightbox.asset.fileName,filters:[{name:'图片',extensions:[lightbox.asset.fileName.split('.').pop()??'png']}]});if(!path)return;try{await writeFile(path,dataUrlBytes(lightbox.asset.dataUrl));onToast('原图已另存为')}catch(cause){onError(cause instanceof Error?cause.message:'另存为失败')}}
  const toggleSelected=(id:string)=>{setSelecting(true);setSelected(values=>{const next=new Set(values);next.has(id)?next.delete(id):next.add(id);return next})}
  const galleryRows=useMemo(()=>galleries.map(gallery=><div key={gallery.id} className={`gallery-list-row${gallery.id===selectedId?' active':''}${renamingId===gallery.id?' renaming':''}`} draggable={renamingId!==gallery.id} onDragStart={event=>event.dataTransfer.setData('text/coolnote-gallery',gallery.id)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();const id=event.dataTransfer.getData('text/coolnote-gallery');if(id&&id!==gallery.id)void dragGallery(id,gallery.id)}}><button className="gallery-list-main" onClick={()=>setSelectedId(gallery.id)} onDoubleClick={()=>{setRenamingId(gallery.id);setRenameValue(gallery.name)}}><Icon name="book-image"/>{renamingId===gallery.id?<input autoFocus value={renameValue} aria-label="重命名画廊" onClick={event=>event.stopPropagation()} onChange={event=>setRenameValue(event.target.value)} onBlur={()=>void rename(gallery)} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();if(event.key==='Escape')setRenamingId(null)}}/>:<><span>{gallery.name}</span><small>{gallery.itemCount}</small></> }</button>{renamingId!==gallery.id&&<span className="gallery-list-actions"><button aria-label={`重命名${gallery.name}`} onClick={()=>{setRenamingId(gallery.id);setRenameValue(gallery.name)}}><Icon name="pencil"/></button><button aria-label={`删除${gallery.name}`} onClick={()=>removeGallery(gallery)}><Icon name="trash-2"/></button></span>}</div>),[galleries,selectedId,renamingId,renameValue])

  if(loading&&!galleries.length)return <><section className="gallery-list-panel" aria-label="正在加载画廊列表" data-collapsed={collapsed}><div className="gallery-list-header"><div className="gallery-list-heading"><strong>画廊</strong></div></div><SidebarSkeleton rows={7}/></section><section className="gallery-panel"><div className="gallery-toolbar"><button className="icon-button panel-toggle" aria-label="折叠画廊列表" onClick={onToggle}><Icon name="panel-left-close"/></button></div><ContentSkeleton cards={6}/></section></>
  return <>
    <section className="gallery-list-panel" data-collapsed={collapsed} aria-label="画廊列表"><div className="gallery-list-header"><div className="gallery-list-heading"><strong>画廊</strong><span className="gallery-count">{galleries.length}</span></div><div className="gallery-list-header-actions"><button className="icon-button" aria-label="新建画廊" onClick={()=>setDraftName('未命名画廊')}><Icon name="plus"/></button></div></div><nav className="gallery-list">{galleryRows}{draftName!==null&&<div className="gallery-list-draft"><Icon name="book-image"/><input autoFocus aria-label="画廊名称" value={draftName} onFocus={event=>event.currentTarget.select()} onChange={event=>setDraftName(event.target.value)} onBlur={()=>void create()} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();if(event.key==='Escape')setDraftName(null)}}/></div>}</nav></section>
    <section className={`gallery-panel${dropActive?' drop-active':''}`} onDragEnter={event=>{if(event.dataTransfer.types.includes('Files')){event.preventDefault();setDropActive(true)}}} onDragOver={event=>{if(event.dataTransfer.types.includes('Files'))event.preventDefault()}} onDragLeave={event=>{if(event.currentTarget===event.target||!event.currentTarget.contains(event.relatedTarget as Node))setDropActive(false)}} onDrop={handleFileDrop}><div className="gallery-toolbar"><button className="icon-button panel-toggle" aria-label={collapsed?'展开画廊列表':'折叠画廊列表'} onClick={onToggle}><Icon name={collapsed?'panel-left-open':'panel-left-close'}/></button><div className="gallery-breadcrumb"><span>画廊</span>{current&&<><Icon name="chevron-right"/><strong>{current.name}</strong></>}</div>{current&&<div className="gallery-toolbar-actions"><span className={`gallery-save-state ${saveState==='保存失败'?'error':''}`}>{saveState}</span><button className="tool-action" onClick={()=>void chooseFiles()}><Icon name="image-up"/>添加图片</button><button className={`tool-action${selecting?' active':''}`} onClick={()=>{setSelecting(value=>!value);setSelected(new Set())}}><Icon name="check-square"/>选择</button><button className="icon-button danger-hover" aria-label="删除画廊" onClick={()=>removeGallery(current)}><Icon name="trash-2"/></button></div>}</div>
      {!current?<div className="gallery-empty"><Icon name="images"/><h1>创建你的第一个画廊</h1><p>积累灵感图片，或在 CoolNote 中展示个人作品。</p><button onClick={()=>setDraftName('未命名画廊')}><Icon name="plus"/>新建画廊</button></div>:<div className="gallery-scroll"><header className="gallery-heading"><div className="gallery-cover"><img src={cover||BUILT_IN_COVERS[0].src} alt="画廊封面"/><div className="gallery-cover-actions"><button ref={coverButtonRef} onClick={()=>setCoverMenu(value=>!value)}><Icon name="image"/>内置图片</button><button onClick={()=>coverUploadRef.current?.click()}><Icon name="image-up"/>上传</button><input ref={coverUploadRef} hidden type="file" accept="image/*" onChange={event=>{const file=event.target.files?.[0];if(file)void fileDataUrl(file).then(value=>{dirty.current=true;setCover(value)}).catch(cause=>onError(cause instanceof Error?cause.message:'无法读取封面'));event.target.value=''}}/></div></div><div className="gallery-heading-copy"><input aria-label="画廊名称" value={name} onChange={event=>{dirty.current=true;setName(event.target.value)}}/><textarea aria-label="画廊介绍" placeholder="写下这个画廊的主题与介绍…" value={introduction} onChange={event=>{dirty.current=true;setIntroduction(event.target.value)}}/></div><FloatingLayer open={coverMenu} anchor={coverButtonRef} placement="bottom-end" className="gallery-cover-picker product-layer" onDismiss={()=>setCoverMenu(false)}>{BUILT_IN_COVERS.map(item=><button key={item.src} aria-label={item.label} className={(cover||BUILT_IN_COVERS[0].src)===item.src?'active':''} onClick={()=>{dirty.current=true;setCover(item.src);setCoverMenu(false)}}><img src={item.src} alt=""/></button>)}</FloatingLayer></header>
        {selecting&&<div className="gallery-selection-bar"><strong>已选择 {selected.size} 张</strong><button aria-label="全选已加载" data-tooltip="全选已加载" onClick={()=>setSelected(new Set(items.map(item=>item.id)))}><Icon name="check-square"/></button><button aria-label="复制到画廊" data-tooltip="复制到画廊" disabled={!selected.size} onClick={()=>setTransfer({ids:[...selected],move:false})}><Icon name="copy"/></button><button aria-label="移动到画廊" data-tooltip="移动到画廊" disabled={!selected.size} onClick={()=>setTransfer({ids:[...selected],move:true})}><Icon name="folder"/></button><button className="danger" aria-label="删除所选图片" data-tooltip="删除所选图片" disabled={!selected.size} onClick={confirmBatchDelete}><Icon name="trash-2"/></button><button aria-label="退出选择" data-tooltip="退出选择" onClick={()=>{setSelecting(false);setSelected(new Set())}}><Icon name="x"/></button></div>}
        {!loading&&!items.length?<button className="gallery-drop-zone" onClick={()=>void chooseFiles()}><Icon name="image-up"/><strong>拖入图片，开始布置画廊</strong><span>支持 JPEG、PNG、WebP、GIF，单张最大 100 MB</span></button>:<div className="gallery-masonry" onDragOver={event=>{if(event.dataTransfer.types.includes('text/coolnote-gallery-item'))event.preventDefault()}} onDrop={event=>{const id=event.dataTransfer.getData('text/coolnote-gallery-item');if(id){event.preventDefault();setDraggingItemId(null);void dragItem(id,null)}}}>{items.map((item,index)=><article key={item.id} className={`gallery-card${selected.has(item.id)?' selected':''}${draggingItemId===item.id?' dragging':''}`} draggable onDragStart={event=>{setDraggingItemId(item.id);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/coolnote-gallery-item',item.id)}} onDragEnd={()=>setDraggingItemId(null)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();event.stopPropagation();setDraggingItemId(null);const id=event.dataTransfer.getData('text/coolnote-gallery-item');if(id&&id!==item.id)void dragItem(id,item.id)}}><button className="gallery-image-button" onClick={()=>selecting?toggleSelected(item.id):void openAt(index)}>{item.thumbnailDataUrl?<img src={item.thumbnailDataUrl} alt={item.originalFileName} loading="lazy" decoding="async" draggable={false}/>:<span className="gallery-missing"><Icon name="image"/>缩略图不可用</span>}{item.isAnimated&&<span className="gif-badge">GIF</span>}</button><button type="button" className={`gallery-check${selected.has(item.id)?' checked':''}`} aria-label={`${selected.has(item.id)?'取消选择':'选择'} ${item.originalFileName}`} onClick={event=>{event.stopPropagation();toggleSelected(item.id)}}><Icon name="check-square"/></button><div className="gallery-card-actions"><button aria-label="复制图片到剪贴板" onClick={event=>{event.stopPropagation();void copyItem(item)}}><Icon name="copy"/></button><button aria-label="移动到其他画廊" onClick={event=>{event.stopPropagation();setTransfer({ids:[item.id],move:true})}}><Icon name="folder"/></button><button aria-label="删除图片" onClick={event=>{event.stopPropagation();void deleteItems([item.id])}}><Icon name="trash-2"/></button></div></article>)}</div>}
        {loading&&<div className="gallery-loading">正在加载画廊…</div>}{items.length<total&&<button className="gallery-load-more" disabled={loadingMore} onClick={()=>selectedId&&void loadItems(selectedId,true)}>{loadingMore?'加载中…':`加载更多（${items.length}/${total}）`}</button>}
      </div>}
      {dropActive&&<div className="gallery-drop-overlay"><Icon name="image-up"/><strong>释放以添加到“{current?.name}”</strong></div>}
    </section>
    <ProductProgressToast toast={importState?{id:importState.id,title:importState.current<importState.total&&!importState.cancelled?'正在导入图片':'导入已结束',current:importState.current,total:importState.total,detail:`已添加 ${importState.added} · 跳过 ${importState.skipped} · 失败 ${importState.failed.length}`,active:importState.current<importState.total&&!importState.cancelled,actionLabel:'取消',onAction:()=>{cancelImport.current=true}}:null} onClose={()=>setImportState(null)}/>
    {transfer&&<div className="gallery-transfer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setTransfer(null)}}><div className="gallery-transfer-dialog" role="dialog" aria-modal="true"><h2>{transfer.move?'移动到画廊':'复制到画廊'}</h2><div>{galleries.filter(gallery=>gallery.id!==selectedId).map(gallery=><button key={gallery.id} onClick={()=>void runTransfer(gallery.id)}><Icon name="image"/><span>{gallery.name}</span><small>{gallery.itemCount}</small></button>)}{galleries.length<2&&<p className="gallery-transfer-empty">请先创建另一个画廊。</p>}</div><button className="cancel" onClick={()=>setTransfer(null)}>取消</button></div></div>}
    {lightbox&&<div className="gallery-lightbox" role="dialog" aria-modal="true" aria-label={lightbox.item.originalFileName}><button className="lightbox-close" aria-label="关闭灯箱" onClick={()=>setLightbox(null)}><Icon name="x"/></button><button className="lightbox-prev" aria-label="上一张" disabled={currentIndex<=0} onClick={()=>void openAt(currentIndex-1)}><Icon name="chevron-right"/></button><div className="lightbox-stage">{lightbox.asset?<img src={lightbox.asset.dataUrl} alt={lightbox.asset.fileName}/>:<div className="gallery-loading">正在读取原图…</div>}<footer><span>{lightbox.item.originalFileName}</span><div><button onClick={()=>void copyLightbox()} disabled={!lightbox.asset}><Icon name="copy"/>复制图片</button><button onClick={()=>void saveLightbox()} disabled={!lightbox.asset}><Icon name="download"/>另存为</button><button onClick={()=>{setTransfer({ids:[lightbox.item.id],move:false});setLightbox(null)}}><Icon name="copy"/>复制到</button><button onClick={()=>{setTransfer({ids:[lightbox.item.id],move:true});setLightbox(null)}}><Icon name="folder"/>移动到</button><button className="danger" onClick={()=>{setLightbox(null);void deleteItems([lightbox.item.id])}}><Icon name="trash-2"/>删除</button></div></footer></div><button className="lightbox-next" aria-label="下一张" disabled={currentIndex<0||currentIndex>=items.length-1} onClick={()=>void openAt(currentIndex+1)}><Icon name="chevron-right"/></button></div>}
  </>
}
